### ISSUE TITLE
No message is displayed if I wrong the password.

### ISSUE THREAD

**Issue by Urahara** [PrivateBin/PrivateBin#476] opened 2019-08-12 11:59 UTC
## Steps to reproduce

1. Create a new snippet
2. Check "Burn after reading" and put a password.
3. Get a link of snippet

### What happens
When i click on link provided it ask me for a password if a put wrong password, no alerts are displayed, only a error in console.

### What should happen

An alert should be displayed indicating that the password is incorrect and enabling me to try again.

## Additional information

_Console:_
> privatebin.js?1.3:4482 failed to decipher data

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by rugk** [comment] 2019-08-12 16:02
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/469

**Closed by rugk** 2019-08-12 16:02 UTC

**Comment by Urahara** [comment] 2019-08-12 16:59
@rugk I see that is the same behaviour, but the snippet should only be deleted after reading, right? If i hit <kgd>F5</kgd> i lose my snippet.

**Comment by rugk** [comment] 2019-08-12 21:37
Yes, that's an issue, but technically still the same as #469. Or https://github.com/PrivateBin/PrivateBin/issues/374 for why the paste has to be deleted even if you enter an incorrect password.
