### ISSUE TITLE
Error on saving paste

### ISSUE THREAD

**Issue by gavinsauder** [PrivateBin/PrivateBin#977] opened 2022-09-07 16:40 UTC
## Steps to reproduce

1. Install in docker: privatebin/fs
2. Saving new paste results in this error: Could not create paste: Error saving paste. Sorry.
3. Also results in this in error logs: 2022/09/07 12:18:38 [error] 19#19: *38 FastCGI sent in stderr: "PHP message: failed to store the server salt, delete tokens, traffic limiter and user icons won't workPHP message: failed to store the traffic limiter, it probably contains outdated informationPHP message: failed to store the purge limiter, skipping purge cycle to avoid getting stuck in a purge loopPHP message: PHP Warning:  mkdir(): Permission denied in /srv/lib/Data/Filesystem.php on line 88" while reading response header from upstream, client: 172.18.0.3, server: , request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:",

## Additional information

![image](https://user-images.githubusercontent.com/40070195/188933132-bb805e6b-6d5b-4100-b272-630f4ed74f8d.png)

## Basic information

**Server address**:

**Server OS:** Ubuntu 20.04.4

**Webserver:** Docker version 20.10.17, build 100c701

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>:  **No**

**Comment by elrido** [comment] 2022-09-18 11:51
Possible duplicate of #475 (and #631, #617, etc.) - As per the containers [read-me file](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/README.md#running-the-image):

>  Note that the volume mounted must be owned by UID 65534 / GID 82. If you run the container in a docker instance with "userns-remap" you need to add your subuid/subgid range to these numbers.

**Closed** 2022-10-25 19:44 UTC
Labels: duplicate
