### ISSUE TITLE
Pastes becomes blank in latest Edge

### ISSUE THREAD

**Issue by sebastiannielsen** [PrivateBin/PrivateBin#474] opened 2019-08-09 09:56 UTC
## Steps to reproduce
Open any paste in Microsoft Edge Version 77.0.235.5 (Official build) dev (64-bit)

### What happens
Paste is blank

### What should happen
The content of the paste should show

## Additional information
![blankpaste](https://user-images.githubusercontent.com/1034930/62771020-8923cc80-ba9c-11e9-81f6-82930bb79f5f.png)

Console log:
privatebin.js?1.3:620 Language 'sv' is not supported. Translation failed, fallback to English.
jQuery.PrivateBin.me.loadTranslations @ privatebin.js?1.3:620
jQuery.PrivateBin.me.init @ privatebin.js?1.3:4814
(anonymous) @ privatebin.js?1.3:29
e @ jquery-3.4.1.js:2
t @ jquery-3.4.1.js:2
setTimeout (async)
(anonymous) @ jquery-3.4.1.js:2
c @ jquery-3.4.1.js:2
fireWith @ jquery-3.4.1.js:2
fire @ jquery-3.4.1.js:2
c @ jquery-3.4.1.js:2
fireWith @ jquery-3.4.1.js:2
ready @ jquery-3.4.1.js:2
B @ jquery-3.4.1.js:2

## Basic information

**Server address:** https://privatebin.net/

**Server OS:**

**Webserver:**

**Browser:** Microsoft Edge Version 77.0.235.5 (Official build) dev (64-bit)

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by r4sas** [comment] 2019-08-09 13:37
Related to #468

**Comment by rugk** [comment] 2019-08-10 09:11
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/468

**Closed by rugk** 2019-08-10 09:11 UTC
Labels: duplicate
