### ISSUE TITLE
Add JS unit tests

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#32] opened 2016-07-10 06:29 UTC
I think this can be done with https://www.browserstack.com/ e.g., but I don't know exactly how do to this.
So if anyone has experience with such a service, please let us know.

**Comment by rugk** [comment] 2016-08-03 19:24
It can also be done with Saucelabs e.g. An FLOSS project using it is e.g. [openpgp.js](https://saucelabs.com/u/openpgpjs).

**Comment by rugk** [comment] 2016-09-14 22:29
And Saucelabs [can be integrated into the Travis build process](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-Sauce-Labs).

**Comment by elrido** [comment] 2017-01-29 15:43
I finally made some progress on this and introduced offline unit tests using [Mocha](http://mochajs.org/) (framework), [JSVerify](http://jsverify.github.io/) (property based tests à la [QuickCheck](https://hackage.haskell.org/package/QuickCheck)) and [Istanbul](http://gotwarlost.github.io/istanbul/) (code coverage). I updated the `tst/README.md` and the [wiki page](https://github.com/PrivateBin/PrivateBin/wiki/Development#javascript) with descriptions on their installation and use.

So far only one function is covered (well, I had three until I realized the latter two [aren't in use anymore](https://github.com/PrivateBin/PrivateBin/issues/165)). The obvious next step is to cover more and more functions, at least of the helper, filter and i18n classes.

Part of the logic in the controller and i18n classes require the full DOM of one of the templates to be present and a server to talk to. For this, running the tests online (in a browser) would be better. Mocha certainly supports this mode, but I am not sure about JSVerify. We can always fall back to the plain [BDD interface](http://mochajs.org/#interfaces) for these.

**Comment by elrido** [comment] 2017-02-12 16:23
All helper functions are now unit tested and I managed to hook Mocha into our Travis CI setup. As discussed I created a branch for this work, so that I can merge the refactoring of the JS into that when it is done. I again found some dead code that I removed and two small corner cases that are now properly handled.

**Comment by rugk** [comment] 2017-02-12 17:37
Be aware that the refactoring is large, so rather don't do anything in the controller. I left the helper however mostly unchanged…

**Comment by elrido** [comment] 2017-04-07 05:01
I just merged the current state of the branch into master, so that the other efforts may benefit of the progress so far. Currently the unit tests cover 47% (532 of 1117) of the statements, 38% (135 of 356) of the code paths and 40% (79 of 196) of the functions in privatebin.js (numbers based on [istanbul output of a unit test run](https://github.com/PrivateBin/PrivateBin/tree/99b0c22bf442059a43055ef73f2e499fbbd4ee87/tst#running-javascript-unit-tests)).

I have recently added static tests for the current PrivateBin v1 paste format and the legacy ZeroBin one (which was using Base64.js v1.7 with its non-standard output, hence our [compatibility option](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#zerobincompatibility)). These are there so that we may do the upcoming changes to the encryption functions with confidence, knowing that we have implemented it in such a way that the old paste formats can still be deciphered if the unit tests pass.

While taking a closer look at that part of the code I also realized that by now most browsers (and JSDom for node JS) offer atob and btoa functions which allow conversion of 8-Bit character sets to Base64 and back. Also, SJCL has such functions, too. As a proof I have included a unit test that does such conversions using these different libraries and compares the results. We could therefore already get rid of Base64.js v2.1.9 (not the v1.7 one, due to the ZeroBin-compatibility mentioned in the previous paragraph). One caveat: As [JS uses UTF-16 strings by default](https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_Unicode_Problem), we still need something equivalent to the btou and utob functions of Base64.js to convert the UTF-16 to UTF-8 and back. The smallest implementation of these (135 lines) might be provided by the [TextEncoderLight library](https://git.daplie.com/coolaj86/TextEncoderLite/blob/master/index.js).

**Comment by cryptomilk** [comment] 2017-04-07 06:11
Ok, the UTF-16 will explain why sometimes uploading pastes from my python script doesn't work. We should settle on UTF-8 for newer versions of the paste format.

**Comment by elrido** [comment] 2017-04-07 07:44
Well, we always used UTF-8 internally before base64 encoding the message (as an aside: all our code files are stored as UTF-8, too), but JS DOMStrings are always UTF-16, so we still need to convert into that encoding on the JS side after unpacking the base64 strings. This is can't be changed as long as our logic gets executed in JS on Browsers.

On the python side AFAIK you usually already have UTF-8 encoded strings, so there should not be anything to do on that end. Of course, if you want to paste any non-UTF-8 text files (say, those from Windows, for example), then you first need to convert them into UTF-8 before encrypting them. 

Note that JSON structures produced by Browsers [may use UTF-16 encoding](https://en.wikipedia.org/wiki/JSON#Data_portability_issues), so you might need to check for that in your code if you implement any decryption logic in python.

**Comment by rugk** [comment] 2017-09-18 12:27
BTW [new Firefox versions also support headless mode](https://developer.mozilla.org/en-US/Firefox/Headless_mode), which can be used for testing stuff.

**Comment by rugk** [comment] 2017-10-11 17:08
Also new testing tool: https://www.cypress.io/

**Comment by elrido** [comment] 2018-04-29 08:11
As of now the unit tests cover 73% (814 of 1118) of the statements, 64% (227 of 355) of the code paths and 77% (151 of 195) of the functions in privatebin.js.

**Comment by elrido** [comment] 2018-05-30 19:17
In order to make it easier to get an environment for the unit testing set up, I replicated our TravisCI environment in a docker container:
https://hub.docker.com/r/privatebin/unit-testing/

No more excuses not to run the unit test suite before committing! :-p

**Closed** 2018-06-30 14:00 UTC
Labels: enhancement

**Comment by elrido** [comment] 2018-06-30 14:50
For the record, here is a list of all the bugs in the JS code that were found in the process of introducing the JS unit testing:
-  fix missing class renaming cae5a7115136f68a5e07e2263d84a15397b42418
-  fixing inconsistency d678f5dada0f4cb8555ebce50ca88f051b2fd1b3
-  removing unused pieces of code (legacy?), resolves #165 368aa2305bf551a9b8ca3c88354c0131d1a1442d
- fixing bug for elements with only one child b992bcc7322617fd215ce29a3f67283b89a897e5
- fixing bug - asterisk is allowed in URLs query string b00bcd1352e1726a3f48309200b79bd9841084a4
- removing dead code b9c05b06d0aa318ac8dd49c1c7f405d37abc3135
- fixing #209, refactoring regression when file upload is disabled cd40717301125d8a4cf638b81395b6f18733ccfc
-  removing dead code dbfb1e83bac66ae25cb84736bed261df85a75697
-  fixing error message display revealed by testing remaining time display function 73bc6851785e2880864b05213e99e8820a70424d
-  removing duplicate code and unused option 28f1f41c176540583e3deff3aa770b93057e6785
-  found and fixed a bug in TopNav.collapseBar() while writing test for it 76debde85b5041aed6317979536d7094046bb65b

While some were new regressions from the (necessary) refactoring, there were also some older issues that hadn't been reported before and some dead code. Since it took so long doing these, there were at least two instances of regressions that were found and reported, before we got there with the testing.

**Comment by elrido** [comment] 2018-07-01 17:21
PS: Two more regressions were found while updating JS libraries during manual, not unit testing. Both are related to the decryption and display of sent comments:
- sending anonymous comments #333
- comments on pretty printed pastes #334

**Comment by elrido** [comment] 2018-07-22 08:35
PPS: Another regression was found and solved just in time before the release:
- force password entry during decryption #341
