### ISSUE TITLE
Can't create big pastes 

### ISSUE THREAD

**Issue by hasufell** [PrivateBin/PrivateBin#327] opened 2018-06-19 01:06 UTC
## Steps to reproduce

1. Try to create a paste between 1 and 2 mb (couldn't figure out the exact size where it fails)

### What happens

frontend says

```
 Could not create paste: server error or not responding
```

server responds with

```
2018/06/19 01:00:28 [crit] 13#13: *143 open() "/var/tmp/nginx/client_body/0000000015" failed (13: Permission denied), client: 000.00.0.0, server: , request: "POST / HTTP/1.1", host: "paste.xxx.xxx"
```

### What should happen

The paste should be created.

## Additional information

This runs on my own server.

## Basic information

**Server OS:** Gentoo, but PrivateBin runs in docker

**Webserver:** [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) as front proxy with the docker container of PrivateBin

**Browser:** tried with firefox 60.0.2 and chrome 67.0.3396.87

**PrivateBin version:** `privatebin/nginx-fpm-alpine:1.1.1`

The size limit in the config is set to a high value (8mb) and the nginx front proxy is configured with `client_max_body_size 0;` to allow arbitrary big body size.

**Comment by r4sas** [comment] 2018-06-19 01:12
Check that user from nginx.conf (default: `user www-data;`) have permissions to write in `/var/tmp/nginx` recursive.

**Comment by elrido** [comment] 2018-06-19 04:14
Just to check, the nginx error is from the privatebin container or the nginx-proxy one? If it's the privatebin one, can you try and attach a volume to /var/tmp in it to see if the nginx/client_body folder gets created or not?

**Comment by hasufell** [comment] 2018-06-19 08:54
> Check that user from nginx.conf (default: user www-data;) have permissions to write in /var/tmp/nginx recursive.

# ls -la /var/tmp/nginx/
total 28
drwx------    7 nginx    nginx         4096 Jun 19 08:47 .
drwxr-xr-x    3 root     root          4096 Jun 19 00:42 ..
drwx------    2 www-data root          4096 Jun 19 00:42 client_body
drwx------    2 www-data root          4096 Jun 19 00:42 fastcgi
drwx------    2 www-data root          4096 Jun 19 00:42 proxy
drwx------    2 www-data root          4096 Jun 19 00:42 scgi
drwx------    2 www-data root          4096 Jun 19 00:42 uwsgi

> Just to check, the nginx error is from the privatebin container or the nginx-proxy one?

privatebin container

> If it's the privatebin one, can you try and attach a volume to /var/tmp in it to see if the nginx/client_body folder gets created or not?

It does not get created, because `/var/tmp/nginx` folder doesn't exist.

**Comment by elrido** [comment] 2018-06-19 11:05
I could reproduce the issue with the privatebin container. It's nginx refuses any POST larger then 1 MiB. If I stay slightly lower I get the permission problem. The folder structure in the container exists, as @hasufell  listed above and nginx runs as the www-data user, so should have access to those, drwx should let it write.

I'll look into it and get back to you. In any case I'll have to adjust the nginx configuration to match the default 2 MiB limit of privatebin.

**Comment by elrido** [comment] 2018-06-19 11:39
Hi @hasufell,

I just committed two changes to the docker repo and the automated image builds in the docker cloud are running as I write this:
1. nginx now runs as user nginx, group www-data. This allows it to create and write into those folders as intended, fixing the permission error. It also better separates the permissions between php-fpm and nginx. Both are in the www-data group and can read from /var/www (the document root), but only php-fpm may write to /srv (the application root, where the data is kept).
2. I increased the max body size setting of nginx to 3 MiB. If the message is larger then 2 MiB, PrivateBin will complain due to its default 2 MiB size limit. If its larger then 3 MiB, nginx will reject it (protecting php from loading it into RAM and exhausting the servers resources).

For your use case of allowing up to 8 MiB pastes / attachments, you would want to [change the nginx.conf](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/etc/nginx/nginx.conf#L70) and can then build your own image or just bind the changed file to /etc/nginx/nginx.conf.

The default max_post_size in php should already be at 8 MiB, but please let me know if that causes you additional problems.

Thank you for reporting this!

**Comment by hasufell** [comment] 2018-06-19 12:18
> For your use case of allowing up to 8 MiB pastes / attachments, you would want to change the nginx.conf and can then build your own image or just bind the changed file to /etc/nginx/nginx.conf.

That is quite annoying to do and can cause weird failures in the future when upstream changes the nginx.conf. The body setting should be set in a separate config file in `/etc/nginx/conf.d/body.conf` or similar, so it can be easily overridden.

**Comment by elrido** [comment] 2018-06-19 14:42
The nginx.conf is entirely under our control, its not the one of upstream. What would you suggest to have as a size? If we have it arbitrarily large, we run the risk of running of memory on the php side, don't we?

**Comment by hasufell** [comment] 2018-06-19 14:48
> The nginx.conf is entirely under our control, its not the one of upstream.

That's what I meant with upstream.

> What would you suggest to have as a size?

Same as now, except in `/etc/nginx/conf.d/body.conf`.

**Comment by elrido** [comment] 2018-06-19 14:49
For just that one setting? Well, if you insist. Feel free to send us a pull request.

**Closed** 2018-06-30 15:29 UTC
