### ISSUE TITLE
URL Shortner via AJAX?

### ISSUE THREAD

**Issue by r3pek** [PrivateBin/PrivateBin#238] opened 2017-07-06 16:41 UTC
## Steps to reproduce

1. setup the urlshortener

### What happens
Currently PrivateBin just calls the configured URL with the paste url attached.

### What should happen
The call should be made via AJAX and the shown URL replaced with the shortened one.

## Basic information

**Server address**: private

**Server OS:** CentOS 7

**Webserver:** Apache 2.4

**Browser:** Firefox 54

**PrivateBin version:** 1.1

* I can reproduce this issue on <https://privatebin.net>: No (no urlshortener configured)

**Comment by rugk** [comment] 2017-07-06 17:13
Yeah, this would be possible, but it should be:
1. optional (to keep the old behaviour), i.e. configurable by the server admin
2. at least only happen when the user clicks on a button, so that pastes are not automatically leaked and the user stays in control

Also the URL shorter needs correct CORS headers, to be configured.

**Comment by r3pek** [comment] 2017-07-06 17:28
1. Totally agree.
2. I think that the option to auto-shorten the links should *not* be available.

I really thought this was the expected behaviour until I used my private YOURLS setup to shorten the URLs and found out it just GETs the page :-(

**Comment by rugk** [comment] 2017-07-06 17:40
> I think that the option to auto-shorten the links should not be available.

That's what I meant. :smile: 

> I really thought this was the expected behaviour until I used my private YOURLS setup to shorten the URLs and found out it just GETs the page :-(

So it literally just shows the URL? That's indeed not a very nice UX.
However, the problem could be that different URL shorters have different APIs and may return the shorturl in a different format. So while YOURLS returns the shorturl in plaintext, another URL shorter may return a JSON or so…

**Comment by r3pek** [comment] 2017-07-06 18:06
`So it literally just shows the URL? That's indeed not a very nice UX.`
Yep
`However, the problem could be that different URL shorters have different APIs and may return the shorturl in a different format. So while YOURLS returns the shorturl in plaintext, another URL shorter may return a JSON or so…`
YOURLS have several "reply types", being one of then just the plain URL (it can also return a JSON structure).
I know that it could be combersome but since it's the suggested URL shortener, I used it expecting it to "just work" :)

**Comment by rugk** [comment] 2017-07-06 19:01
Well… yeah, that's totally understandable.

**Comment by Micsi** [comment] 2018-01-19 15:32
same here. I tried [Polr](https://polrproject.org) in addition to YOURLS. As well there is only an AJAX API, no url GET param as expected from PrivateBin.
The api differ so you need a special configuration for YOURLS and another for POLR and so on...

Does anyone know if there is an URL shortener available that works with PrivateBin as is?

**Comment by elrido** [comment] 2018-01-19 21:07
I am using Yourls as documented in its [API](http://yourls.org/#API) quite successfully. With a public Yourls instance (=everyone can use it without credentials) it is this URL format:
https://example.com/yourls-api.php?action=shorturl&format=simple&url=

**Comment by elrido** [comment] 2018-01-19 21:10
Oh, and Polr claims to have a [GET API](https://docs.polrproject.org/en/latest/developer-guide/api/#api-endpoints) too:
http://example.com/api/v2/action/shorten?key=API_KEY_HERE&url=

**Comment by celevra** [comment] 2018-05-08 18:29
if pull requests are welcome i will do it
at first only the get variant
is there allready a way implemented to get settings in javascript from conf.php?

**Comment by rugk** [comment] 2018-05-08 19:08
A PR would be great. Keep in mind the whole paste is fetched over AJAX soon (see https://github.com/PrivateBin/PrivateBin/pull/216). Maybe have a look for how it is done there, too. (Or maybe wait until that is merged? – or base your changes upon that, if needed.)

> is there allready a way implemented to get settings in javascript from conf.php?

No and in that way, it will likely also not be implemented, as one of course don't want to have access to the DB password from the outside. :smile: 
Currently all settings are managed in the HTML file.

But your idea is generally good, as it helps for other things. I've opened https://github.com/PrivateBin/PrivateBin/issues/312 for it, but that is a future issue. Currently you may just use the HTML file to "transport" settings.

**Comment by Amgine0** [comment] 2018-10-24 14:32
NB: YOURLS is modular, and CORS compliance is an [optional plugin](https://github.com/TEODE/yourls-access-control-allow-origin/blob/master/plugin.php "TEODE/yourls-access-control-allow-origin"). Its API also supports POST, as noted by elrido.

**Comment by MrAureliusR** [comment] 2018-12-21 00:56
I just went through the whole rigamarole of setting up POLR (which, by the way, is great software, if the install is a bit finnicky) and as others reported, it just GETs the URL given. This is bad because my POLR is self-hosted and set to private, and it exposes the API key in the URL.

Was there ever any progress on this? It returns the URL as either plain text or JSON. I believe other shorteners do the same.

**Comment by elrido** [comment] 2018-12-21 10:18
As explained above, we support onlz the GET syntax of POLR and that seems to work, but only makes sense with public instances. That was the scope of this ticket and no other plans exist to my knowledge. If you want to provide a different implementation in this project, any pull requests are very welcome.

**Comment by MrAureliusR** [comment] 2018-12-22 00:34
@elrido I understand that, but when I click "Shorten" it literally just redirects the browser to a plaintext page with the URL there. The URL in the browser includes the API key. Am I doing something wrong? Is PrivateBin supposed to display the received URL instead of redirecting the browser?

**Comment by elrido** [comment] 2018-12-22 07:03
Not at all, what you describe is exactly the expected behaviour. It is up to the URL shortener to provide a UI for itself. PB just hands off the generated URL to the shortener and that's all there is to it from our end. On that page you simply ctrl+a then ctrl+c and then go and paste/ctrl+v that URL into your mail or reddit thread or what ever. Simple.

As said, we are open for anyone providing pull requests if a different behaviour is expected.

**Comment by celevra** [comment] 2018-12-22 07:16
@mraureliusr I'm not sure if my changes are in the actual code base but if they are you simply have to use the config option 
urlshortenerajax
Instead of 
urlshortener
And everything should be as you expect it

**Comment by elrido** [comment] 2020-02-02 06:52
This should have been addressed with #480

**Closed by elrido** 2020-02-02 06:52 UTC
Labels: enhancement

**Comment by rugk** [comment] 2021-05-06 19:45
@sushinger That depends solely on the URL shorter you use. It has nothing to do with PrivateBin.
