### ISSUE TITLE
v1.2.1 works however 1.3 doesn't

### ISSUE THREAD

**Issue by LaurenceMillward** [PrivateBin/PrivateBin#473] opened 2019-08-07 09:20 UTC
Steps to reproduce

1. Fresh install of Ubuntu 18 (ubuntu-bionic-18.04-amd64-server-20190722)
2. Install dependencies (sudo apt-get install -y apache2 php7.2 php7.2-xml php7.2-mbstring php7.2-mysql php7.2-json php7.2-pdo)
3. Download Pirvatebin 1.3 and try to create a paste. (no edits to config files etc, just a clean as-is approach)

Cloudflare / CDNs etc are non existent for this test. It's just a plain instance in AWS. 

### What happens
1.3 errors with  "Could not create paste: server error or not responding"
1.2.1 works fine. 

### What should happen
1.3 should just work like 1.2.1 does.

## Additional information
Error being thrown in Chrome Dev Tools when "Sending" a paste on 1.3
```
privatebin.js?1.3:3856 parsererror SyntaxError: Unexpected end of JSON input
    at parse (<anonymous>)
    at jquery-3.4.1.js:2
    at l (jquery-3.4.1.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.4.1.js:2)
```

When clicking into error it points towards this: 
  ```
      /**
         * actually uploads the data
         *
         * @name   ServerInteraction.run
         * @function
         */
        me.run = function()
        {
            let isPost = Object.keys(data).length > 0,
                ajaxParams = {
                    type: isPost ? 'POST' : 'GET',
                    url: url,
                    headers: ajaxHeaders,
                    dataType: 'json',
                    success: function(result) {
                        if (result.status === 0) {
                            success(0, result);
                        } else if (result.status === 1) {
                            fail(1, result);
                        } else {
                            fail(2, result);
                        }
                    }
                };
            if (isPost) {
                ajaxParams.data = JSON.stringify(data);
            }
            $.ajax(ajaxParams).fail(function(jqXHR, textStatus, errorThrown) {
                console.error(textStatus, errorThrown);
                fail(3, jqXHR);
            });
        };
```

       

## Basic information

http://35.177.134.164/PrivateBin-1.3/ 
http://35.177.134.164/PrivateBin-1.2.1/

ubuntu-bionic-18.04-amd64-server-20190722

Apache

Version 75.0.3770.142 (Official Build) (64-bit) (Chrome)

**Comment by LaurenceMillward** [comment] 2019-08-07 09:24
Oh and yes I followed the FAQ & ran the script to fix permissions on the files / folders just to rule that out.

**Comment by elrido** [comment] 2019-08-08 10:06
That error message is generated in the PHP logic on the server side. Basically something between your browser and the PHP process did prevent the json_decode function to receive the full JSON string. If you don't use CDNs, this is likely a restriction in the web server configuration or the PHP ini.

You may want to debug it by dumping this line on the server side logic:
https://github.com/PrivateBin/PrivateBin/blob/master/lib/Request.php#L112

If the cut off is always at a specific length of the message, you may find out which of our configurations would limit the requests to that size. Or maybe you find some other reason why these messages fail to be parsed as JSON strings (trailing characters, etc.).

**Comment by rugk** [comment] 2019-08-08 10:26
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/470

**Closed by rugk** 2019-08-08 10:26 UTC
