### ISSUE TITLE
Add "My Pastes" page with stored URLs for pastes in a cookie

### ISSUE THREAD

**Issue by techboyg5** [PrivateBin/PrivateBin#722] opened 2020-11-22 18:07 UTC
Whenever a paste is created, a cookie should be set in the browser containing the URL for that paste.

Then, you can go to the "My Pastes" page, where content and links to each paste will be.

**Comment by rugk** [comment] 2020-11-22 18:30
Looks like a dupe of #2? Is this your idea?

**Comment by rugk** [comment] 2020-11-22 18:30
Duplicate of #2

**Closed by rugk** 2020-11-22 18:30 UTC
Labels: enhancement
