### ISSUE TITLE
I have not set password, but my pastes requires a passwrod and I don't know how to remove. I am using webbased (not installed)

### ISSUE THREAD

**Issue by 51525355** [PrivateBin/PrivateBin#730] opened 2021-01-03 10:55 UTC
## Steps to reproduce

1.
2.

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes / No

**Comment by rugk** [comment] 2021-01-03 17:43
When a password is requested even though no-one is set, this suggests that the decryption failed. PrivateBin cannot detect the reason and thus just always asks for the password.

Please ensure you use an up-to-date version of PrivateBin and your browser.
E.g. the old Edge (with it's own engine) is known to cause problems, see https://github.com/PrivateBin/PrivateBin/issues/676.

Also please fill out the issue template next time you report a bug.

**Comment by rugk** [comment] 2021-01-03 17:44
Guessing and closing as a dupe of https://github.com/PrivateBin/PrivateBin/issues/676 unless more details are provided.

**Closed by rugk** 2021-01-03 17:44 UTC
