### ISSUE TITLE
No preview shows for any options on fresh install in Chrome

### ISSUE THREAD

**Issue by ssx** [PrivateBin/PrivateBin#483] opened 2019-08-14 20:39 UTC
## Steps to reproduce

1. Visit https://bin.smr82.net
2. Enter data in text area

### What happens
1. Nothing shows in preview tab

### What should happen
1. Preview should contain the text entered or source code highlighted 

## Basic information

**Server address**: https://bin.smr82.net

**Server OS:** Ubuntu 18.04

**Webserver:** nginx 1.15.8, PHP 7.2.20

**Browser:** Version 76.0.3809.100

**PrivateBin version:** 1.3

I can reproduce this issue on <https://privatebin.net>: No

**Comment by r4sas** [comment] 2019-08-14 22:43
Chrome/Chromium?

Version 67.0.3396.87 without issues.

**Comment by war59312** [comment] 2019-08-15 00:20
Same here

Broken in Chrome Version 78.0.3880.4 (Official Build) dev (64-bit) on Win10 1903 x64

Nothing reported in Console

Fine on Edge and IE shows loading forever (odd, since nothing about IE at FAQ @ https://github.com/PrivateBin/PrivateBin/wiki/FAQ - Seems IE not supported, should say that

**Comment by r4sas** [comment] 2019-08-15 04:31
> Same here

Any screenshots?
Maybe here any style problem?

> You really better upgrade or risk getting "hacked" quickly.

I know which sites I visit, so that doesn’t threaten me.

**Comment by elrido** [comment] 2019-08-17 08:16
@ssx & @war59312 - I tried to reproduce this on https://bin.smr82.net, it works on Firefox 68.0.2 and Chromium 76.0.3809.100 on Ubuntu 18.04. Since you seem to only have this issue on that server, but not on privatebin.net (the demo site running the 1.3 docker container), is it maybe a plugin that interferes with just that one URL for some reason?

I can't debug it, if I can't reproduce this, unfortunately. :-(

**Comment by ssx** [comment] 2019-08-17 08:26
That’s an odd one! I’ll see if I can debug further to shed some light on it.


From: El RIDO <notifications@github.com> <notifications@github.com>
Reply: PrivateBin/PrivateBin
<reply@reply.github.com>
<reply@reply.github.com>
Date: 17 August 2019 at 09:16:44
To: PrivateBin/PrivateBin <privatebin@noreply.github.com>
<privatebin@noreply.github.com>
CC: Scott Robinson <scott@dor.ky> <scott@dor.ky>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [PrivateBin/PrivateBin] [bug] No preview shows for any
options on fresh install (#483)

@ssx <https://github.com/ssx> & @war59312 <https://github.com/war59312> - I

**Comment by war59312** [comment] 2019-08-18 18:29
FYI, mine is at https://www.war59312.com/bin/

No plugins installed. Pretty much default install, other than name

BTW, it's not just the preview. After I create the paste, it shows up blank as well.

**Comment by Haocen** [comment] 2019-08-19 00:58
@war59312 cannot reproduce on Windows 10.
Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by ssx** [comment] 2019-08-20 19:56
Same with my install - default install and that tab just doesn't work at all.

Chrome Version 76.0.3809.100.

Same in normal and incognito mode.

**Comment by Haocen** [comment] 2019-08-20 21:57
@ssx do you happen to see anything in developer console?

**Comment by war59312** [comment] 2019-08-21 02:27
OK, I'll keep trying to duplicate.

FYI, happens on https://privatebin.net/ too for me

**Comment by Haocen** [comment] 2019-08-21 02:30
@war59312 can you take a look in developer console?

**Comment by war59312** [comment] 2019-08-21 02:37
Well a second ago it was blank on privatebin.net but now I just got:

`Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAGVUABEAAAAAxuQAAQABAAAAAAAAAAAAAAAAAAAAAAAAAABHREVGAAABgAAAAC4AAAA0ArgC7UdQT1MAAAGwAAAQ6AAALgxKsqRTR1NVQgAAEpgAAAH3AAAELqI5y+RPUy8yAAAUkAAAAE8AAABgaGyBu2NtYXAAABTgAAABlAAAAkQkRATXY3Z0IAAAFnQAAABeAAAAugDsQf1mcGdtAAAW1AAABZcAAAvNb3/BHGdhc3AAABxsAAAACAAAAAgAAAAQZ2x5ZgAAHHQAAEApAAB3CtbiupxoZWFkAABcoAAAADYAAAA2BkubWWhoZWEAAFzYAAAAIAAAACQHFARfaG10eAAAXPgAAAI6AAAEEk4TN4Nsb2NhAABfNAAAAhIAAAISiLhpam1heHAAAGFIAAAAIAAAACACigzgbmFtZQAAYWgAAACUAAABHhQGLdJwb3N0AABh/AAAAq4AAASRk5y6n3ByZ...QxUajCCFt4p9HP4fzdSWs2XhWl5HvJazrIrFUyB0l5dpqcW10lV2wukjMLuAvyMHNiYpgPsrCVXZDKrkpll6UWkh7kABVAFVCDe7UFmxagDegA+hLHRPbqtMo7ZHCpKdT6tPGXybzo0+RXBLoPZt1tELcXxCmAAyZwYTJvdDFZKnDER44X2451rDqCyunIsRWvLSx6wnWqwPj/uX5/KuEy6DL0z6A/Fn79VihxMFJsrlAFy4DpZOcvNlMeNp+BRDLj0r+XFdRxdSNSNxiI/AL3ojKdAAB4AWPw3sFwIihiIyNjX+QGxp0cDBwMyQUbGdictkUwWDAwsDJogTgOPN4c9iz6bMos4iysHFChUDZXJnMWTSZZJrAQt9M+YQYBBh4GTgY2kEZOoJiA0z4GBxiEiDEzuGxUYewIjNjg0BGxkTnFZaMaiLeLo4GBkcWhIzkkAqQkEggceHw5HFkM2VRZJFlYebR2MP5v3cDSu5GJwWUDW9xG1hQXAFAmKZU=' because it violates the following Content Security Policy directive: "font-src 'self'".`

`Refused to load the font 'data:application/font-woff2;charset=utf-8;base64,d09GMgABAAAAAGhEABIAAAABHTwAAGfcAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP0ZGVE0cGkIb6mQchSwGYACHRggiCYRlERQKg4kcguJFC4R0AAE2AiQDiWQEIAWUNQeKcAyBP1s1BnGGvLUbRYp/twNW4z5vtdmB2u0osd3MvxYnx3XQHRzHVCy7s////z8nqYyxbeb+AyloVrAyLCITWUY5YTREN4p6VWFQr6R4m1riOFCoc1aZTTaMFUFGONjoCA4jQwQbtjmumdTkcfBiYykrw8oZynDdIuENbUxvGnuco8suSg/tPRwfWbe4d14bDvnZ5pkzdW061zFEPqlWcqN4Sb5oTJwI9vlNU+aFQsCZcKeraCZ+Zxulrbqq1aTb5uXdjLccpmaKCAQb5z9NtmnQjeZ6zb9svOnmSOkMzMnfQnAzfr2MZyW7Z+miWF9c/MxsIhHqyZ...gSr+kPN6pJ2WULfJstA8ys+fXvWSfdUgOZZZFVNtnlkFM+MuQqvxsxRXk74aDe62qFog2l497IdVSkgnuSuZBPvBNxA5FS8dqb0krk0YauAVcc0G0rEaGc8inDVshehi1uRTe/6/PpxSKx+JAr+a/AKUcQKlfD3xqYTO0V15WQTCbedAFyJK+16Gr8ZDsk3C1EmdzwRgoCCqxQ5IurMgnc7UEWC3lNOBQyuGQVeoO3kCtWaeBP4yQ3MJwkYOQKs3Xz2EgjVR5EXVd3NzZcpQx6oiDJLEkkErhbLY8Mm6isNbcXOkShjS7ETGY7+I07vYwO0WUWVuwu5trmdR35WKjfwe+2CnV/lWU6xRbsQA0Ghc3JbNkuqd/SW2ShEtUI8gNk/9ozBJngXXdNNqkiy1uFHuhWpaRbBMnwkjeuDe+DYNgLSWTPCVdrASJuREpG2EbENUhiQ4JmoulkSkRB5NolgmsHIsmhFItZRN2E/BxJbUItQ7SNpTRTAd0QAA==' because it violates the following Content Security Policy directive: "font-src 'self'".`

**Comment by Haocen** [comment] 2019-08-21 02:40
Cool! I believe the content security policy is the root cause, any chance you modify your own deployment and replace the following part:
`font-src 'self'`
With:
`font-src 'self' data:`

**Comment by war59312** [comment] 2019-08-21 02:43
To be clear that was on privatebin.net that gave the above errors. So looks like it needs to be fixed.

On my own site, it's already set correctly, as in:

`cspheader = "default-src 'none'; manifest-src 'self'; connect-src *; script-src 'self' 'unsafe-eval'; style-src 'self'; font-src 'self' data:; img-src 'self' data: blob:; media-src blob:; object-src blob:; sandbox allow-same-origin allow-scripts allow-forms allow-popups allow-modals"`

And nothing in crome console being reported on my site

**Comment by Haocen** [comment] 2019-08-21 02:44
Alright, I can confirm this is probably caused by one of your browser plug-ins where it try to load something on the page you're reading.

Some antivirus such as Kaspersky also does this.

**Comment by war59312** [comment] 2019-08-21 02:52
No antivirus and happens with all Extensions disabled.

No proxy, no ad filtering, no nothing.

Also, I meant to say. Old version, 1.2.1, does NOT have this issue.

That is https://www.war59312.com/oldbin/ works fine. Preview and posts show up fine.

**Comment by Haocen** [comment] 2019-08-21 02:55
Ok I'm allocating resource for reproducing the bug now.

Will install Ubuntu 18.04 and Chrome next.

Do you mind take a screenshot of what it looks like?

**Comment by war59312** [comment] 2019-08-21 02:59
Version 1.2.1 @ https://www.war59312.com/oldbin/ working correctly:

![1 2 1](https://user-images.githubusercontent.com/106354/63399259-f76e6600-c39d-11e9-8a54-a57b09d48a8e.PNG)

Version 1.3 @ https://www.war59312.com/bin/ NOT working correctly:

![1 3](https://user-images.githubusercontent.com/106354/63399264-fb9a8380-c39d-11e9-8605-0a711f1a440a.PNG)

**Comment by Haocen** [comment] 2019-08-21 03:05
Thank you!

Just boot into install mode with
en_windows_10_consumer_editions_version_1903_x64_dvd_b980e68c.iso

**Comment by elrido** [comment] 2019-08-21 04:03
Why is a font loaded via a data string? The only fonts I know we use in the project [are the ones from bootstrap](https://github.com/PrivateBin/PrivateBin/tree/master/css/bootstrap/fonts), so the CSP rule `font-src 'self'` should be sufficient. It really looks like something is injecting content into your browser tab that isn't from us. Pretty scary! :fearful:

**Comment by war59312** [comment] 2019-08-21 05:20
@elrido , doesn't sound good.. I'll check into it.

Though, for sure looks like a font:

![Font](https://user-images.githubusercontent.com/106354/63404610-d9126580-c3b1-11e9-95d3-f0c0e25a0b37.PNG)

**Comment by Haocen** [comment] 2019-08-24 00:31
I'm able to reproduce the bug, it seemed the bug is introduced in their dev branch.

And it is **NOT** related to font loaded via data url during my test, no error printed in my console.

Need more time to investigate and record videos.

**Comment by Haocen** [comment] 2019-08-24 00:51
Pin point the problem to be related to jQuery, during a call to `DOMPurify.sanitize` on following line:
```
https://www.war59312.com/bin/js/privatebin.js?1.3:2217
```
Where the code is:
```
sanitizedLinkedText = DOMPurify.sanitize(escapedLinkedText);
```
Detailed error:
```
message: "Failed to execute 'invoke' on 'CreateHTMLCallback': The provided callback is no longer runnable."
stack: "Error: Failed to execute 'invoke' on 'CreateHTMLCallback': The provided callback is no longer runnable.↵    at Function.u.sanitize (https://www.war59312.com/bin/js/purify-1.0.11.js:1:7723)↵    at eval (eval at parsePaste (https://www.war59312.com/bin/js/privatebin.js?1.3:2218:13), <anonymous>:1:33)↵    at parsePaste (https://www.war59312.com/bin/js/privatebin.js?1.3:2218:13)↵    at Object.jQuery.PrivateBin.me.run (https://www.war59312.com/bin/js/privatebin.js?1.3:2371:17)↵    at HTMLAnchorElement.viewPreview (https://www.war59312.com/bin/js/privatebin.js?1.3:2058:25)↵    at HTMLAnchorElement.dispatch (https://www.war59312.com/bin/js/jquery-3.4.1.js:2:42571)↵    at HTMLAnchorElement.v.handle (https://www.war59312.com/bin/js/jquery-3.4.1.js:2:40572)"
```

**Comment by Haocen** [comment] 2019-08-24 00:54
In 1.2.1 the return value of `DOMPurify.sanitize` is:
![correct return value](https://user-images.githubusercontent.com/10842569/63630362-e3b64000-c5e7-11e9-96a8-8fef1c385e91.png)

In 1.3 the return value of `DOMPurify.sanitize` is:
![broken return value](https://user-images.githubusercontent.com/10842569/63630367-efa20200-c5e7-11e9-912e-16745df746e9.png)

en_windows_10_consumer_editions_version_1903_x64_dvd_b980e68c.iso
Windows 10 Pro
1903
18362.30

Google Chrome
Version 78.0.3887.7 (Official Build) dev (64-bit)

**Comment by Haocen** [comment] 2019-08-24 03:34
@ssx Could you please kindly let us know the version of Chrome you're running?

**Comment by elrido** [comment] 2019-08-24 04:40
Ok, that would explain why it affects only 1.3: We upgraded the purify JS version from 1.0.7 to 1.0.11. If this does hit mainstream Chrome(ium) versions, lets open a ticket with the upstream and when they fixed it, release a fixed version in 1.3.1.

For reference, in Chromium 76.0.3809.100 I can't (yet) reproduce the issue.

The font problem shouldn't prevent the app to run and may stem from plugins like [Grammarly](https://stackoverflow.com/a/50672596) or [Web of Trust](https://stackoverflow.com/a/52154024).

**Comment by ssx** [comment] 2019-08-25 19:44
Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by Haocen** [comment] 2019-08-25 20:03
OK, thanks for double confirming, I saw you put in the same issue in the main issue, just want to make sure.

I'm just tried following combination:
Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Mac OS 10.14.6 (18G87)

With your website https://bin.smr82.net but was not able to reproduce the problem.

I'm allocating resource to test it on Windows.

**Comment by elrido** [comment] 2019-09-14 08:15
Allright, @rugk pointed us to the solution to the puzzle: As of Chrome 77 this (in all other browsers completely unsupported) feature is enabled by default and the upstream released a patch for this with DOMpurify 2.0.0. See https://github.com/cure53/DOMPurify/issues/361 for the details.

Have to say, Chrome devs start to really behave like the IE ones back in the Netscape/IE browser war of the 90ies. Create their own standards, implement them without coordination with W3C, etc.

Anyhow, I'll add a reminder to upgrade DOMpurify in the next dot release.

**Comment by war59312** [comment] 2019-09-14 20:06
FYI working again as of:

Google Chrome Version 78.0.3904.9 (Official Build) dev (64-bit)

**Comment by rugk** [comment] 2019-09-17 07:25
So closing this as fixed.

**Closed by rugk** 2019-09-17 07:25 UTC
Labels: bug
