### ISSUE TITLE
URL is not geting parsed into a link

### ISSUE THREAD

**Issue by dausruddin** [PrivateBin/PrivateBin#579] opened 2020-01-31 15:49 UTC
## Steps to reproduce

1. Paste any link
2. Submit as plain text

### What happens
URL is not clickable.

### What should happen
URL should be parsed into link and can be clicked

## Additional information

I was using 1.3.1 and URL can be clicked. After upgraded to 1.3.2, URL is treated as plain text and cannot be clicked.
I am able to reproduce the bug on https://privatebin.net/?ceda6a2ccb7137b9#C3j4gX84trhafqeLvuYwaFAyJmnciASAaMvf3RAjoJLz

## Basic information

**Server address**:

**Server OS:** Ubuntu 18.04

**Webserver:** Nginx 1.16.1

**Browser:** Firefox 72.0.2

**PrivateBin version:** 1.3.2

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by dausruddin** [comment] 2020-01-31 16:00
I just realized even in preview, it will not parse the link

**Comment by rugk** [comment] 2020-01-31 18:04
The reason is because you selected the "source code/text only" mode. To see clickable links, do use the "Markdown" version.

So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.

**Comment by dausruddin** [comment] 2020-01-31 18:39
That is weird because before this, URLs are still got parsed in plain text. mode.

**Comment by rugk** [comment] 2020-01-31 18:41
Okay, is this a bug @elrido?

**Comment by elrido** [comment] 2020-01-31 19:48
definitely a regression, that used to work

**Comment by dausruddin** [comment] 2020-01-31 20:10
I can reproduce that old behavior in https://bin.moritz-fromm.de/?86e3ed0fc2f7e125#BLq9CP3pHx3z1Qt58kkdF9FHzcLL9YQ5wLVzsAT2voDo

This website is using 1.3.1 according to what is says at the bottom.

**Comment by elrido** [comment] 2020-01-31 22:03
Looked at what was changed between 1.3.1 and 1.3.2 in that area - I think it might be the revert to the stricter HTML entity encoding done in [4bf7f863d](https://github.com/PrivateBin/PrivateBin/commit/4bf7f863dc2ffea1ea105e575205ab0f83ed2751#diff-cf28a0bc390eee2482509aca8212f831L2365-R2406) we now encode forward slashes (`/`), so the links don't get recognized anymore (i.e. `http:**//**`).

We encode the slashes as per the OWASP recommendation in [rule #1](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#rule-1---html-escape-before-inserting-untrusted-data-into-html-element-content) that states:

> the forward slash is included as it helps to end an HTML entity

Since it is still getting sanitized using DOMPurify just one line after, I'm tending to risk allowing the slashes in this case.

@rugk , would that be fine for you as well?

**Comment by rugk** [comment] 2020-02-01 14:27
Yeah, do allow it then.

**Closed** 2020-02-02 06:11 UTC
Labels: bug

**Comment by elrido** [comment] 2020-02-02 06:13
There was another issue that I discovered and fixed while working on this: DOMpurify removed our magnet links, as they didn't fit it's pattern of allowed URL schemes.
