### ISSUE TITLE
raw text tail text after <<""<

### ISSUE THREAD

**Issue by andrew-ld** [PrivateBin/PrivateBin#422] opened 2019-04-18 10:03 UTC
## Steps to reproduce

1. create new document with `<<""<<owo`
2. open raw text

### What happens
`<owo`  is not shown

### What should happen
the raw text should also show that part

## Basic information

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by rugk** [comment] 2019-04-18 13:14
Likely a dupe of https://github.com/PrivateBin/PrivateBin/issues/403

**Closed by rugk** 2019-04-18 13:14 UTC
