### ISSUE TITLE
Add an edit feature that shows a history of changes with diff

### ISSUE THREAD

**Issue by 9mido** [PrivateBin/PrivateBin#761] opened 2021-03-31 19:34 UTC
https://github.com/bartTC/dpaste

https://dpaste.org/

Dpaste uses an edit feature which is very useful to make changes and show the changes when sharing your paste link multiple times with someone else. That other person can edit your code and show you what needs to be changed. It shows what lines need to be changed without guessing, which saves time. 

It also shows a history of changes in a separate URL https://dpaste.org/history/ and it shows a diff of those changes as well above the actual code in the URL you are working with. It also shows a count of number of lines added vs removed. 

Each time an edit is made, a new URL is created but the changes get tracked temporarily. When the paste expires, everything will be deleted. 

One idea would be to allow the privatebin user to toggle this feature on or off because maybe they don't want their changes to be temporarily tracked via history or diff while some privatebin users will want to see a diff and history of changes. Maybe encrypt the history / diff of each edited change so it cannot be intercepted.

Dpaste also allows users to click on each line of code so that it gets highlighted. But this is discussed in another issue already. 

![Screen Shot 2021-03-31 at 3 31 44 PM](https://user-images.githubusercontent.com/60831272/113200630-90ca5300-9236-11eb-8692-9f585546e942.png)
![Screen Shot 2021-03-31 at 3 32 21 PM](https://user-images.githubusercontent.com/60831272/113200632-90ca5300-9236-11eb-80d3-71374093521d.png)

**Comment by rugk** [comment] 2021-04-01 19:18
Hmm, this is basically an extended version of https://github.com/PrivateBin/PrivateBin/issues/255. Given that even multiple versions of a paste are hard enough to implement, it's not likely this will happen any time soon.
Also note PrivateBin is e2e encrypted, in contrast to dpaste, as far as I see.

**Comment by 9mido** [comment] 2021-04-01 19:55
Thanks for the reply. Since saving a history of each version is tough to implement, what about for now just implement the edit/ diff part? After a paste gets edited, show the diff from the previous change to the edited change. Holding off on the version history can be added later. 

In the dpaste code models.py (database file) https://github.com/bartTC/dpaste/blob/master/dpaste/models.py#L60-L67 it shows the parent snippet being tracked in the database. 

It uses https://docs.python.org/3/library/difflib.html for tracking diff changes. It takes the parent paste in the database and does a diff on the current paste. 

https://github.com/bartTC/dpaste/blob/master/dpaste/views.py#L213-L245

It seems to track versions in the session or session storage. 

I am not sure what the PHP equivalents of these are but that is how it is done in Python.

**Comment by elrido** [comment] 2021-04-02 06:31
Editing an existing paste requires the concept of a user or other means of authentication to the server. This runs counter to the idea of the server having "zero-knowledge". Maybe the editing could be tied to the deletion token? So there would be an editing link, like there is a deletion link and a view link?

It would in any case require a significant change to how the internal paste storage classes interface to each other, as at the moment it is designed around the concept of these pastes being all write once and read-only. That is why in #255 we considered versioned pastes instead - these would all be independent pastes, but linked in a parent/child and tree-like fashion (similar to commits in git, for example). That way there is no need to change the internal workings of the storage subsystem and anyone could create a new paste based on an existing one and would not need to authenticate itself with the server.

Due to the above points, I consider this a major rewrite of the application. If anyone picks this up, let me know if you have any questions on the workings of the [Data classes](https://github.com/PrivateBin/PrivateBin/tree/master/lib/Data) and their unit tests.

**Comment by elrido** [comment] 2022-04-30 07:37
duplicate of #114

**Closed by elrido** 2022-04-30 07:37 UTC
Labels: duplicate, enhancement
