### ISSUE TITLE
Pasting this code will resulting in a password protected paste when I never set a password

### ISSUE THREAD

**Issue by psycholyzern** [PrivateBin/PrivateBin#440] opened 2019-06-15 15:42 UTC
## Steps to reproduce

1. paste [this code](https://pastebin.com/a84Jx4ve) in any public or private privatebin server
2. submit

### What happens
It ask for password when I never set a password.

### What should happen
No password should be asked

## Basic information

**Server address**: https://privatebin.net/

**Server OS:** -

**Webserver:** -

**Browser:** - 

**PrivateBin version:** 1.2.1

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by elrido** [comment] 2019-06-15 16:04
duplicate of #260, can't reproduce anymore on the latest (unreleased) master branch. See [test instance](http://zerobin-test.dssr.ch/).

**Closed** 2019-06-15 16:04 UTC

**Comment by psycholyzern** [comment] 2019-06-16 13:44
When will it be released?

**Comment by elrido** [comment] 2019-06-16 17:21
It is being discussed at the moment among the maintainers. We may release the current state within the next few weeks. The [1.3 release board](https://github.com/PrivateBin/PrivateBin/projects/3) should give you a good picture, the main features are done.
