### ISSUE TITLE
Add new format: links

### ISSUE THREAD

**Issue by dausruddin** [PrivateBin/PrivateBin#585] opened 2020-02-13 14:26 UTC
Hi. I want to make a feature request. After a few problems I had with links, so this is my suggestion.

Make a new format for links. Basically in this format, everything line started with known URL protocol will be turned into URLs.

What do you guys think?
I wanted to make this by my own but I don't even know where to start.

Please consider this. Thanks.

**Comment by rugk** [comment] 2020-02-14 15:43
Links should automatically be converted (in text format), this has been fixed in https://github.com/PrivateBin/PrivateBin/issues/579.

So I guess this is a duplicate of https://github.com/PrivateBin/PrivateBin/issues/579.

**Closed by rugk** 2020-02-14 15:43 UTC

**Comment by dausruddin** [comment] 2020-02-14 16:14
Unfortunately there is always something lacking.
I have reported some and right now I found another character that breaks a URL like apostrophe (`'`) which can be used in a file name. Who know which other character would break next right?

So I am suggesting a format for links where any line of text started with a valid URL protocol will be converted into a URL until the end of the line. So no need to check for a URL validity anymore. I am not sure about any security threat tho.

This is merely a suggestion.

**Comment by elrido** [comment] 2020-02-15 06:08
Yes, there is a number of characters that you can't use in a URL, as they have special meaning as delimiters, are reserved or need to be encoded when used in HTML. In all of these cases, you should be able to [percent-encode](https://tools.ietf.org/html/rfc3986#section-2.1) them (also called URL encoding).

Your browser will do this encoding for you, if you enter a URL with such characters in the address bar, hit enter to load the URL and then copy it out of the address bar again (the address bar will likely hide the encoding when displaying the URL, but the copy will contain the encoded characters). Your apostrophe should get turned into the sequence `%27` and that URL would get detected.

You can find the full URL detection regex here:
https://github.com/PrivateBin/PrivateBin/blob/12c83a13c77eb9246e9bf94e112bb51494390905/js/privatebin.js#L301
