### ISSUE TITLE
[FEATURE] Please provide an API to paste encrypted blobs

### ISSUE THREAD

**Issue by cryptomilk** [PrivateBin/PrivateBin#185] opened 2017-02-16 10:33 UTC
It would be nice to have an API to create a new bin for webtools (curl, python-requests) to paste directly from the command line.

I'm running cpaste.org and switched to PrivateBin now. I offered a tool https://git.cryptomilk.org/projects/cpaste.git/tree/cpaste to upload pastes from the command line. I would like to have the same with PrivateBin. We could do the encryption locally with python and then push an encrypted blobs to the PrivateBin instance.

**Comment by rugk** [comment] 2017-02-16 15:44
There is an API: https://github.com/PrivateBin/PrivateBin/wiki/API
Dupe of https://github.com/PrivateBin/PrivateBin/issues/105 e.g.

**Closed by rugk** 2017-02-16 15:44 UTC

**Comment by cryptomilk** [comment] 2017-02-16 17:43
Could you link it under Further resources in the main README.md?

**Comment by rugk** [comment] 2017-02-16 17:54
It's in the Wiki and I think who wants to find them (not many people…) should be able to find them. I may add a "more" link though.
