### ISSUE TITLE
Problem with variable name = "" in cfg.php

### ISSUE THREAD

**Issue by ZerooCool** [PrivateBin/PrivateBin#641] opened 2020-06-21 02:03 UTC
Hello,
I modified the name variable to have a title corresponding to my expectations, at the top of the page, in the title tag.

I note that in the message displayed by default, at the bottom right, the value privatebin is also replaced by the name of my site, except, in my opinion, if the one who set it up wanted to do well, this is not is not consistent, because, here, I could completely delete the word PrivateBin, to appropriate the content, which is not my intention, but, by modifying the title and using the name of my domain, that ready to confusion, because, beside my title, I left "- PrivateBin".

You would think that the project was created by me, and, therefore, that I try to assimilate it as a personal creation.

Therefore, I wonder if it is really necessary that the variable name also changes this keyword, bottom right, in the content.

Visionduweb - PrivateBin is a 'pastebin' (or manager of text and source code extracts)

https://privatebin.visionduweb.fr

**Comment by elrido** [comment] 2020-06-22 17:46
closing this as a duplicate of #639 - it seems that this is indeed a separate use case then what we have currently implemented as a "total conversion".

**Closed by elrido** 2020-06-22 17:46 UTC
Labels: duplicate
