### ISSUE TITLE
Accommodate the needs of both users and devs (Composer's vendor dir)

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#84] opened 2016-08-17 18:36 UTC
@elrido wrote in https://github.com/PrivateBin/PrivateBin/pull/65#issuecomment-240192097:
> You saw the ticket by the admin that checked out the project and had issues. If we provide no vendor folder, how many such tickets do you think we would get? Do you honestly think we can expect every user of this project to read a long winded installation procedure. They try it, but from most cases where it fails we never even hear from.

> PrivateBin should just be about copying a few files on the server, not about having to then install non-packaged thirdparty tools (composer is neither in Debians nor Ubuntus default package sources) to then run commands on the commandline (how should those with some FTP-account on a cheap sharehoster do that) to complete the installation. Composer is cool for devs, but we can't expect its use (and availability) from every kid that just wants to run the project on its FTP, raspberry pi or whatnot (yes, I am aware that composer runs on ARM, but that's not the point).

So okay, I agree
* that we should make the installation really easy
* a simple download of a ZIP and it's extraction should be all users need to do

However I also see that
* Contributing to this project can be tricky, because Composer is not intended to use pre-composed vendor files
* It is bad practise - [according to the Composer devs](https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md) - to include the vendor dir

The official reasons for this are (copied from FAQ):

1. Large VCS repository size and diffs when you update code.
2. Duplication of the history of all your dependencies in your own VCS.
3. Adding dependencies installed via git to a git repo will show them as submodules. This is problematic because they are not real submodules, and you will run into issues.

So my comments:

1. may be bad, but think it is acceptable.
2. is not nice, but I can live with it.
3. is *currently* no issue, because we use no module with git submodules, but we might use it in the future, so this might indeed be an issue for us

So we must find a solution, which is good both for devs and users:
* Users should only need to download a ZIP or `git clone` this repo and it should be usable
* Devs should be able to use it and easily contribute to this project

Maybe the last part can partially be addressed by https://github.com/PrivateBin/PrivateBin/pull/83 and the user part is currently possible.

However what I propose to accommodate both needs is:
* We need two branches: One for dev (`master`), and one for users (`stable`)
* We might even set the default branch to `stable` so users who clone PrivateBin without looking at the branches or so, get the right version
* Then we could only include all files necessary for development in the `stable` branch and leave the dev branch for developing. A small `.sh` script could help us to automate this task. (I can do this script.)
* If we set `stable` as default we include a **big** note in the PR template that contributors have to compare their changes to the `stable` branch. Also in the Contributing guide it must be listed. As Contributors (hopefully) read that guide anyway, we can catch their attention. At least it may be easier to catch their attention than users who just clone the repo from the first page they visit.
* We could also block changes to the `stable` branch, so that no one accidentally modifies it.

(Additional) reasons for that:
* The current master also includes unnecessary files for production, such as the whole `tsts/` dir, these could be removed reducing needed disk space
* We could use `stable` as a rolling release, where we push changes every week or so, which provides additional stability for users which used `git clone`.
* We could theoretically also just provide minified files (JS, css and so on) in the `stable` branch, while using usual files in the development branch.

I think, this is the reason for branches in git and they are great for solving our problem.

**Comment by elrido** [comment] 2016-08-18 04:49
Ok look, how is it an issue that we have the code checked in for you as a developer? As you pointed out all three of their arguments don't apply to us (or we actually have a different opinion on them as I would _like_ to keep the history of changes in files between versions: It makes searching for newly introduced bugs so much easier).

Lets say you are a new dev:

1. You check out the repo.
2. You install composer.
3. You change something composer related (need a new library, want to use a newer version of one that we use already, etc.)
4. You run `composer install --no-dev --optimize-autoloader` or `composer update --no-dev --optimize-autoloader`.
5. composer replaces any files that changed.
6. [skipping the part where the dev develops and runs phpunit to ensure all is still working]
7. (Thanks to your change in the .gitignore, @rugk) Your git tells you what changed in vendor or other parts and you check it in.
8. All is well.

Were is the problem with that workflow?

**Comment by rugk** [comment] 2016-08-18 15:38
Yeah, maybe with my PR it could get better, but 7. is the weak point. Files may not be committed

And 4. is not clear for Contributors. How should one know to run this? Usually a dev would just run `composer require XY` and `composer install`.
But if the new .gitignore turns out to be working well, it might really be not that bad.
However note that i listed more reasons for this switch than just the dev experience. Take e.g. the useless `tst` dir for servers.

**Comment by elrido** [comment] 2016-08-19 04:19
The points 2., 3., 4. & 5. only need to be done if you add a new composer component or if you want to update them. Regular dev just runs 1., 6., 7. and hopefully 8. and doesn't even need to care about composer at all.

And yes, point 7. is a general weakpoint in every CVS. It might work well in your local repo, but then you forget to check something in and it breaks for everybody else. Travis should help us detect these cases, as it reruns the unit tests in a clean environment.

**Comment by rugk** [comment] 2016-08-20 09:56
Mhh, okay, so as long as it all works, it is okay. So we might look how further PRs work.

But you still have not commented about the tst dir. This would be a clear advantage of a stable branch.

**Comment by elrido** [comment] 2016-08-20 17:05
The stuff thats in .gitexports is all stuff that is not required for simply running it. README.md etc. is also not required to run it, strictly speaking. I would not unnecessarily complicate the development process by having to constantly remove dirs before merging with master and then later readd them again.

We all agree that admins should use the releases, currently the use the master because the last one is more then 10 months ago and missing some apparently interesting features. If those admins dont remove the tst or doc on their server its their wasted space (disregarding the wasted space and bandwidth of downloading the whole history).

**Comment by rugk** [comment] 2016-08-20 17:14
> I would **not** unnecessarily complicate the development process by having to constantly remove dirs before merging with master and then later readd them again.

You wanted to say it the other way around? Did not you?

Also: With two branches no one has to delete or readd dirs. Every heard of `git checkout`? :wink: 

> The stuff thats in .gitexports is all stuff that is not required for simply running it.

There is no such file.

> If those admins dont remove the tst or doc on their server its their wasted space (disregarding the wasted space and bandwidth of downloading the whole history).

Ha, and if they do they may get problems when doing `git pull`. No that's not a good solution.

**Comment by elrido** [comment] 2016-08-20 18:35
No I meant it as said: I would _not_ have two branches with different sets of files. How do you merge the two branches without deleting tst, etc.?

> There is no such file.

correction: .gitattributes

Bottom line: We should have two branches, but both will have the tst, doc, etc.

**Comment by rugk** [comment] 2016-08-20 19:12
> I would not have two branches with different sets of files. How do you merge the two branches without deleting tst, etc.?

Oh, ah. That's indeed a good point.
But one contra argument: If we only do it (as I suppose as we should only push version to the stable branch), we can indeed use a tiny `mergestable.sh` script, which does this:

```sh
#!/bin/sh
git checkout stable
git merge master
rm -rf tst
```
(untested)

So we would only need to run one comamnd (`./mergestable.sh`) instead of the two git commands, which are already included in the script.

> Bottom line: We should have two branches, but both will have the tst, doc, etc.

Hmm, in this case I would not see any benefit in two branches. Only the "we can push releases to stable later" and can test the code on `master` before releasing it.

**Comment by elrido** [comment] 2016-08-21 05:50
Lets just keep it the way it is for now. We can rediscuss it later if we have more developers.

**Closed by elrido** 2016-08-21 05:50 UTC

**Comment by jelhan** [comment] 2017-01-25 09:55
Just a short note: You should not gitignore the `composer.lock` file since that one allows a reproductive installation of requirements. If you run `composer install` it installs all requirements at version specified in `composer.lock` (if there is any). It has been added to `.gitignore` with these commit https://github.com/PrivateBin/PrivateBin/commit/47b5d315f629ddf6d50481b9001604f191ef0a58.

**Comment by rugk** [comment] 2017-01-25 15:42
Thanks, done in https://github.com/PrivateBin/PrivateBin/commit/065f5e53b381f1e809d762afe5335ca93bdfd337.

**Comment by elrido** [comment] 2017-01-29 14:13
FYI: I readded it to .gitignore in 339ab5e, because I accidentally checked mine in and had to amend my commit. This was probably the original reason why it was ignored in the first place. Added a comment as a reminder why its there.

**Comment by jelhan** [comment] 2017-01-29 21:47
I do not understand why you decided to not follow normal composer workflow. Normally you would do it this way:

* Generate a `composer.json` containing basic project informations (e.g. name, description, author, homepage). Normally done by `composer init`.
* Define project dependencies in `composer.json`. Normally done by `composer require <package>`.
* Composer automatically generates and updates a `composer.lock` file. This one contains the exact versions of each dependency and is used by `composer install`. If you update your dependencies using `composer update` it updates `composer.lock` and afterwards installing new versions defined in `composer.lock`.

You should commit projects `composer.json` and `composer.lock` since these combination allows reproducible setups among developers. _Basic usage_ guide of composer is very clear about that:

> Commit your application's composer.lock (along with composer.json) into version control.
> 
> This is important because the install command checks if a lock file is present, and if it is, it downloads the versions specified there (regardless of what composer.json says).
> 
> This means that anyone who sets up the project will download the exact same version of the dependencies. Your CI server, production machines, other developers in your team, everything and everyone runs on the same dependencies, which mitigates the potential for bugs affecting only some parts of the deployments. Even if you develop alone, in six months when reinstalling the project you can feel confident the dependencies installed are still working even if your dependencies released many new versions since then.
> 
> If no composer.lock file exists, Composer will read the dependencies and versions from composer.json and create the lock file after executing the update or the install command.
> 
> This means that if any of the dependencies get a new version, you won't get the updates automatically. To update to the new version, use the update command. This will fetch the latest matching versions (according to your composer.json file) and also update the lock file with the new version.

Since `composer.lock` allows to have reproducible builds `vendor` folder should be ignored. But if you decide to include vendor folder or parts of it in your repo definitely should include `composer.lock` otherwise `composer install` will change files included in your repo if at least one dependency has a newer version.

Also your continuous integration might give false positive or false negative results if you don't commit `composer.lock`. Your travis setup contains a `composer install -n` which will install newest available versions (in defined range) on every build. This may also dependencies included in vendor dir. So there might be false positive results if a newer version of a dependency fixes a bug which is relevant for this project and there might be false negative results if a newer version breaks something.

I'm using npm and bower quite often. Both doesn't have a `composer.lock` equivalent strategy as default. Seeing issues like the ones mentioned before quite often. Of course the same idea exists in npms world ([npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap), [shrinkpack](https://github.com/JamieMason/shrinkpack), [yarn](https://yarnpkg.com/)). In bower it's still an [open issue](https://github.com/bower/bower/issues/505).

**Comment by elrido** [comment] 2017-01-30 06:11
Dear @jelhan,

composer.json is checked in and the builds are reproducible for other developers.

The reason why we do not follow the composer workflow intended is that this repository should just work when checked out. We do not want to force server admins to install and use composer to install this project. Ideally they just copy the files from a release tar-ball to the server and thats it.

Note that our composer.json forces the two libraries to be specific versions. We decide when we upgrade them, not composer. In the build on travis composer install is executed so that the require-dev section is installed, which is required for some of the static code checkers to be called after the build with the results.

I do like the composer idea, but I don't like that it isn't cleanly packaged for major Linux distros and that they want to force you to use a particular workflow. Our workflow, BTW is described in [this comment above](https://github.com/PrivateBin/PrivateBin/issues/84#issuecomment-240623208).

**Comment by jelhan** [comment] 2017-01-30 09:12
> Note that our composer.json forces the two libraries to be specific versions. We decide when we upgrade them, not composer.

I'm sorry but that's not true. You are using [caret operator](https://getcomposer.org/doc/articles/versions.md#caret): `"paragonie/random_compat": "^2.0"` and `"yzalis/identicon": "^1.1"`. This resolves to >=2.0.0 and <3.0.0 for paragonie/random_compat and >= 1.1.0 and < 2.0.0 for yzalis/identicon.

**Comment by elrido** [comment] 2017-01-30 19:40
Thanks for pointing this out. My understanding was that it would allow only point releases (eg. 2.0 allowing 2.0.4 but not 2.1), not any release higher then that. I fixed the version numbers in 920f02e.

**Comment by jelhan** [comment] 2017-01-31 11:38
Please note that pinning version only fixes part of the issue. Required dependencies might themselves declare dependencies which are not pinned to an exact version. Since both only declare dev dependencies you might not see a problem now but you should keep that in mind. It might result in tests failing in ci but not locally (different version of dependencies dependencies) and you should care about when adding another dependency which has non-dev dependencies.

**Comment by rugk** [comment] 2017-01-31 13:29
So why can't we just include the `composer.lock` in the repo? @elrido you said you "accidentally checked your one in". IMHO this is exactly what is wanted - why should not one check it in?

(I remember I added the file to .gitignore, because a "foreign" `composer.lock` caused some issues, but I am not sure anymore, whether it was just my bad.)

**Comment by elrido** [comment] 2017-01-31 18:16
Because checking it in breaks the build process? Which one do you want to check in, the prod or the dev one? The prod would be what you'd want to have in master which people install on their servers, but the build would need the dev one (or none).

I honestly start to consider getting rid of composer and just manually maintaining the two libraries we need. At least then we would not loose our valuable time with these kind of circular discussions. :-(

**Comment by rugk** [comment] 2017-01-31 19:10
Good argument although I would decide for the dev version as your idea is to make the productive version usable without composer, so in production  no one should run composer anyway.

In any case just let me say that I am fine with the current state - it's of course contradicts to some principles, but at least it works…
