### ISSUE TITLE
Microsoft Edge prompts for password even when one is not used

### ISSUE THREAD

**Issue by Arjun42** [PrivateBin/PrivateBin#515] opened 2019-09-05 22:25 UTC
## Steps to reproduce

1. Create PrivateBin link without a password using Chrome or Firefox
2. Launch Microsoft Edge
3. Go to your instance of PrivateBin (tested on https://privatebin.net and https://vim.cx)
4. Go to link from step 1

### What happens
Prompts for password. "Please enter the password for this paste:"

### What should happen
Text entered in step 1 should display. 

## Additional information

Link works as expected in Chrome and Firefox.  This _may_ be related to issue #468 .  

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

Microsoft Edge 44.17763.1.0

1.3

I can reproduce this issue on <https://privatebin.net>: Yes / No
Yes

**Comment by elrido** [comment] 2019-09-06 07:37
This is a duplicate of #468 - as we discovered [over there](https://github.com/PrivateBin/PrivateBin/issues/468#issuecomment-520117147), Edge (non-Chromium) hasn't implemented SHA256 in Webcrypto, which makes it unable to de- or encrypt either the v1 or the v2 paste formats. You'll have to wait for MS to release the chromium based Edge and hope they don't restrict the webcrypto API in there.

**Closed by elrido** 2019-09-06 07:37 UTC
Labels: duplicate
