### ISSUE TITLE
httpwarning on Tor hidden service

### ISSUE THREAD

**Issue by the-rocinante** [PrivateBin/PrivateBin#747] opened 2021-02-13 06:15 UTC
## Steps to reproduce

1. make PrivateBin 1.3.4 available via Tor .onion address
2. browse to PrivateBin

### What happens

A textual warning appears as follows.

> PrivateBin requires a modern browser to work. Firefox, Opera, Chrome…
> For more information see this FAQ entry.
> Your browser may require an HTTPS connection to support the WebCrypto API. Try switching to HTTPS.

### What should happen

As per cfg/conf.php
> ; Secure transport methods like Tor and I2P domains are automatically whitelisted.

## Additional information

![PrivateBin-Tor onion-httpwarning](https://user-images.githubusercontent.com/76429671/107843379-7debe400-6d98-11eb-9b22-7be1e778b9d4.jpg)

## Basic information

**Server OS:** Ubuntu 20.04 x86_64

**Webserver:** Apache/2.4.41

**Browser:** Brave, Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)

**PrivateBin version:** 1.3.4

I can reproduce this issue on <https://privatebin.net>: No

**Comment by rugk** [comment] 2021-02-13 13:28
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/537

**Comment by rugk** [comment] 2021-02-13 13:29
(TL;DR is: WASM is disabled in Tor Browser. You can enable it at your own risk though.)

**Closed by rugk** 2021-02-13 13:28 UTC
