### ISSUE TITLE
Attachemnt cannot be downloaded/previewed properly if over 10MB

### ISSUE THREAD

**Issue by Haocen** [PrivateBin/PrivateBin#486] opened 2019-08-16 02:30 UTC
## Steps to reproduce

1. Change nginx.conf and php.ini to accept post body of over 10MB
2. Upload a file of 10MB to a paste
3. Load and decrypt the paste

### What happens
the file cannot be downloaded or previewed(if supported), may due to content security policy?

### What should happen
the file should be able to be downloaded or previewed

## Basic information

**Server address**:
N/A

**Server OS:**
docker nginx-fpm-alpine

**Webserver:**
N/A

**Browser:**
Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**PrivateBin version:**
1.2.1
I can reproduce this issue on <https://privatebin.net>: No, because file upload is not enabled.

**Comment by Haocen** [comment] 2019-08-16 02:45
Confirmed video(mov) will not preview because CSP.
File will not download because data url too long, may need to introduce third party library.

**Comment by Haocen** [comment] 2019-08-16 03:15
Need following pieces to be implemented before considered usable:
1. progressive encryption
2. resumable upload
3. resumable download
4. burn after read support big file?

Investigate how mega did their in browser file transfer and encrypt/decrypt.

**Comment by elrido** [comment] 2019-08-16 06:20
Before you loose too much time on this: It was already solved in the 1.3 release by [switching to blob URIs](438).

**Comment by elrido** [comment] 2019-08-16 06:22
duplicate of #432

**Closed by elrido** 2019-08-16 06:22 UTC
Labels: duplicate
