### ISSUE TITLE
[Feature] Separate (curl friendly) url for fetching raw text

### ISSUE THREAD

**Issue by ylogx** [PrivateBin/PrivateBin#287] opened 2018-02-24 05:12 UTC
### What happens
Raw page is generated by clicking on the raw button and rendered using js. 

### What should happen
Clicking on raw page button should take user to a separate page `<host>/raw?asdfasdfasdf`

This will enable users to use curl to fetch the content.

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by rugk** [comment] 2018-02-24 10:37
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/234

Also documented in the FAQ: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#can-i-uploaddownload-the-pastes-with-curlwget

**Closed by rugk** 2018-02-24 10:37 UTC
Labels: duplicate
