### ISSUE TITLE
Unable to download from a Chrome based browser. Firefox works fine.

### ISSUE THREAD

**Issue by eneerge** [PrivateBin/PrivateBin#670] opened 2020-07-20 20:30 UTC
## Steps to reproduce

1. Create a secure link with an attachment
2. Attempt to download in a Chrome based browser on Windows

### What happens
Download does not work and this is reported in the console:
`Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set`

### What should happen
File should download.

## Additional information

I have been using this for a while now without any issue. However, I am now unable to download from Chrome and I have not changed anything on the server end. The only thing I know that may have changed is Chrome because of auto updating.

## Basic information

**Server address**:
not public

**Server OS:**
Server 2012 R2

**Webserver:**
IIS 8.5.9600.16384

**Browser:**
Chrome, but Firefox works fine.

**PrivateBin version:**
1.3.4

I can reproduce this issue on <https://privatebin.net>: Yes / No
No, because it does not support attaching files. The issue I'm hitting is when attaching files.

**Comment by eneerge** [comment] 2020-07-20 20:36
https://www.chromestatus.com/feature/5706745674465280

**Comment by eneerge** [comment] 2020-07-20 21:24
Temporary workaround with security degradation:
Comment out line 343 in lib\Controller.php

`//header('Content-Security-Policy: ' . $this->_conf->getKey('cspheader'));`

**Comment by eneerge** [comment] 2020-07-20 21:28
Real fix:
add "allow-downloads" to the cfg\conf.php

`cspheader = "default-src 'none'; manifest-src 'self'; connect-src * blob:; script-src 'self' 'unsafe-eval'; style-src 'self'; font-src 'self'; img-src 'self' data: blob:; media-src blob:; object-src blob:; sandbox allow-same-origin allow-scripts allow-forms allow-popups allow-modals allow-downloads"`

**Comment by rugk** [comment] 2020-07-21 13:09
This is a known issue and fixed, as you said, by adjusting the CSP. 

Closing this as a duplicate of https://github.com/PrivateBin/PrivateBin/issues/634#issuecomment-642149280

**Closed by rugk** 2020-07-21 13:09 UTC
