### ISSUE TITLE
Filesystem data to MySql migration

### ISSUE THREAD

**Issue by Square252** [PrivateBin/PrivateBin#844] opened 2021-10-07 20:58 UTC
Hi,

So far i found some issues discussing this (#359 and #321) but had no luck at finding a solution.
In one the Issues (#359 ) I found a ruby script, but it seems like the script is outdated and not working for the current format of the pastes.
I tried updating it, but had no luck so far (probably because i don't know any ruby :smile: )...

Has anyone a working solution or a tip for this?

**Comment by rugk** [comment] 2021-10-09 12:17
Probably better to keep the discussion in one place, as such I'm going to mark this as a dupe. Feel free to use the other issue and ping the author of the script there, maybe they know or could adjust that script.

**Comment by rugk** [comment] 2021-10-09 12:17
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/359

**Closed by rugk** 2021-10-09 12:17 UTC
