### ISSUE TITLE
Data folders are not removed automatically

### ISSUE THREAD

**Issue by snafus-io** [PrivateBin/PrivateBin#911] opened 2022-04-04 09:38 UTC
If I take look in the data folder, i got the following files: 
 purge_limiter.php; 
 salt.php; 
 traffic_limiter.php;

Privatebin also stores some Folders with random names like "a4" , "45" which seems to contain the data from the pastes.

But why these Folders still remain if the paste is deleted or expired ?
I expected that these would automatically removed.

How can i fix it ?

**Comment by elrido** [comment] 2022-04-04 17:16
This is a duplicate of #101 - please see over there for the reason we shouldn't delete these folder upon deletion. Maybe it would make more sense to just pre-create all 256*256 needed folders from the start, to avoid this question?

**Closed** 2022-04-06 23:50 UTC
Labels: duplicate
