### ISSUE TITLE
[Feature] Automatically switch to dark theme based on client's system preference

### ISSUE THREAD

**Issue by Haocen** [PrivateBin/PrivateBin#596] opened 2020-03-09 09:58 UTC
## Steps to reproduce

1. When my phone/laptop is in dark mode.
2. Go to privatebin.net

### What happens
The default theme make me blind.
But switching to dark theme does not give me enough color contrast during day.

### What should happen
The theme should switch automatically.

## Additional information

I've implemented this feature with the help of css:

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

and bootswatch 3:

https://bootswatch.com/3/slate/

## Basic information

**Server address**:

I've implemented it here:

https://privatebin-staging.herokuapp.com/

![dark](https://user-images.githubusercontent.com/10842569/76199692-b8cbbc00-61c6-11ea-8c97-b7093f8c8433.PNG)
![dark2](https://user-images.githubusercontent.com/10842569/76199701-bbc6ac80-61c6-11ea-97d9-185b1493dde3.PNG)

To switch preferred color scheme in Chrome dev tool:

![switch to dark](https://user-images.githubusercontent.com/10842569/76199683-b49f9e80-61c6-11ea-8b98-8c7b6bfab9f8.PNG)

Or you may come back after dark if you have dark theme set to auto in your system preference.

The implementation is quite simple but I found it very hard to incorporate with existing darkstrap theme since it is controlled by serverside.

My proposal would be remove darkstrap completely and adopt serverside controlled theme with a simple css class. This will give us additional benefit as we can allow client to switch theme with a
button click(JavaScript toggle css class).

**Server OS:**
N/A

**Webserver:**
N/A

**Browser:**
N/A

**PrivateBin version:**
1.2.1

I can reproduce this issue on <https://privatebin.net>: No

**Comment by rugk** [comment] 2020-03-09 11:54
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/433

**Closed by rugk** 2020-03-09 11:54 UTC
