### ISSUE TITLE
How to use curl to paste bin as follow:

### ISSUE THREAD

**Issue by findmorenow** [PrivateBin/PrivateBin#385] opened 2018-12-11 13:58 UTC
How to use curl to paste bin as follow:
I use bench.sh to test vps and make a bench.log in root folder.
Then I want to curl this log to PrivateBin site, as https://privatebin.net.
These are success demo in the bench.sh code:

sharetest() {
	case $1 in
	'ubuntu')
		share_link=$( curl -v --data-urlencode "container@$log" "https://paste.ubuntu.com" 2>&1 | \
			grep "Location" | awk '{print $3}' );;
	'haste' )
		share_link=$( curl -X POST -s -d "$(cat $log)" https://hastebin.com/documents | awk -F '"' '{print "https://hastebin.com/"$4}' );;
	'clbin' )
		share_link=$( curl -sF 'clbin=<-' https://clbin.com < $log );;
	'ptpb' )
		share_link=$( curl -F c=@- https://ptpb.pw/?u=1 < $log );;
	esac

	# print result info
	echo " Share result:"
	echo " $share_link"
	echo ""

}

**Comment by rugk** [comment] 2018-12-11 15:14
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/221

**Closed by rugk** 2018-12-11 15:14 UTC
