### ISSUE TITLE
Allow edit feature to update streaming links 

### ISSUE THREAD

**Issue by trimechee** [PrivateBin/PrivateBin#1441] opened 2024-10-27 10:38 UTC
Hello, thank you so much for this vital great amazing project and online service ! 💯 🥇 

We hope please an option to modify and edit our posts, because I use online PrivateBin to save a copy of my post on streaming websites and access it easily but many streaming sites are censored, and their url address changes constantly and I have to update their url address, thanks :)

**Comment by elrido** [comment] 2024-10-27 14:20
closed as duplicate of #114 - see that issues discussion why this is technically very challenging and was decided not to get implemented. See also #255 for an alternative idea that could be done, but no one has picked it up yet.

**Closed by elrido** 2024-10-27 14:20 UTC
Labels: duplicate, enhancement
