### ISSUE TITLE
Pastbin does not work. It says, "Could not create paste: server error or not responding." This has been for a couple weeks now.

### ISSUE THREAD

**Issue by EricDunlap819** [PrivateBin/PrivateBin#539] opened 2019-11-04 19:09 UTC
## Steps to reproduce

1.
2.

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes / No

**Comment by r4sas** [comment] 2019-11-04 19:21
Telepaths on vacation. Fill issue form.

**Comment by LickTheCheese** [comment] 2019-11-24 22:47
i have the same issue

it appears that its not actually a server side issue, from looking at my browser console
```javascript
parsererror SyntaxError: Unexpected token < in JSON at position 0
    at parse (<anonymous>)
    at jquery-3.4.1.js:2
    at l (jquery-3.4.1.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.4.1.js:2)
``

**Comment by elrido** [comment] 2020-01-05 13:58
Unfortunately we have insufficient information to help you figuring out what the issue is. I'll close this for now. Please feel free to reopen it when you have collected and updated basic information in your issue description, @EricDunlap819 or @LickTheCheese

**Closed by elrido** 2020-01-05 13:58 UTC
