### ISSUE TITLE
Improve internationalisation (i18n)

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#316] opened 2018-05-21 16:34 UTC
From https://github.com/PrivateBin/PrivateBin/pull/314#issuecomment-390678443:

>- **a missing single source of correct translation keys** (there's no en.json?)
[…]
>- **translation keys which are very long and prone to breakage**
What if someone changes a single char in one of the english strings, I think currently this would break all translations? Wouldn't it be better to work with short key-like constants/strings as keys and then having an en.json for the actual full sentences?

**Comment by elrido** [comment] 2018-05-22 05:08
The first is not an issue, since we have a php unit test that checks that all json files contain the same keys. So any json file can serve as template for a new language.

The second point is a deliberate design choice. I did not invent the usage of full strings vs. IDs, this is how gettext workes since the early 90ies. The big benefit is that as a programmer I do not have to look up what a particular error means when I encounter it in the code and it avoids copy/paste mistakes that cause the wrong message to be displayed because the ID wasn't changed. Also it avoids ever exposing meaningless IDs to the user (ever seen one of those "Error 1234 occurred" messages?) if a message is not translated. In the current solution it just falls back to the default en string.

I would therefore strongly advise against these "improvements" as they IMHO are actually regressions.

**Comment by rugk** [comment] 2018-05-22 08:29
1. is an issue since contributors want a default English file they can copy and translate. Most translators likely only can translate English to their language. As it is currently the English strings are of course included in all langauges, but that is what 2. wants to change, so you have to see them both.
2. That totally depends on the translation system. Of course, they should fall back to English, but that is easy to do – they also just need to use the English `en.json` then.

In general I e.g. really like the way WebExtensions (browser add-ons) are translated. You have [a simple API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n) and some JSON files. And the code automatically [selects the correct language for a string.](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization#Localized_string_selection)

If we then had a reqal translation platform, this would automatically handle the issue of changed English strings and mark the corresponding translation strings as "fuzzy". That means they need re-translation. As the English change may only be minor changes, the translated version of the string is still used.
Only when we change major stuff in the English strings, we could change the translation ID, so it has to be re-translated. But this may not often be the case.

/cc @micschk

----

Generally, we could also have a look at things like https://pontoon.mozilla.org/ or maybe https://projectfluent.org/.

**Comment by elrido** [comment] 2018-05-27 05:32
1. We do have that: Take any current JSON and you do have the English defaults in it as the message ID and just replace the translations with the ones for your language.
2. The translators are not the only audience we address with the translation system. You also need to consider the developers (you and me). If I am deep in the source code, say, creating a new error message to display to the user, then I don't want to first, get to a translation file and figure out what the current highest number for the "ERROR_MESSAGE_X" is or check if "FOO_ERROR" is already taken. I can just write a human readable error description, knowing the context of the error. Also when I read code be someone else (or from myself 5 years ago) I immediately understand what a check is about, if it is followed by a human readable error instead of a message ID that I then need to look up in another file. 

In general I regard this as a total non-issue: All previous 10 translators did not have an issue with the current system. The proposed improvements introduce bugs and are much more fragile then the current system. I absolutely don't ever want to show to users a generic "GREETING_1" string instead of the untranslated English fallback.

**Comment by rugk** [comment] 2018-05-27 08:07
As for 2. of course the devs have to choose reasonable IDs. E.g. "errorPasteLoadingError" is perfectly clear to me and I don't really care whether it is translated as "The paste could not load. We are sorry." or "There was a paste loading error." or "We have to apologize for your inconvenience, but we had one big issue currently and we cannot resolve it: We could not load the paste, that you wanted to load us. We are so sorry.".

Especially as you can see by the last (exaggerated, I know) example at least I consider good ID strings even more readable than whole translations.

As for the English fallback, we'll only show this for 2 or three seconds until the JSON would be loaded. What I often do is just to hardcode the English strings into the HTML then, those which are loaded by JS may need to be shown later then…
But yes, our current translation system could have some issues, especially as it by defaults only loads one JSON – the English fallback JSON would need to be loaded again, afterwards.

**Comment by elrido** [comment] 2018-05-27 12:45
You misunderstand my point in 2.: What about the case where a dev adds a new message ID in the code, but forgets to ever add it even to a single translation file? In that case with the proposed system, this would only be discovered when someone checks the browser console or if a user complains what "errorPasteLoadingError" is supposed to mean.

And the unit test would not catch this, as it compares the translation files for identical message IDs, but doesn't scan the code (which we would then need to do for both JS and PHP).

And as you said, for a fallback we would have to load yet another file from the server, further slowing the UI down.

This is why all major, professional translation frameworks (not just gettext) have switched to full IDs vs abstract ones. It's a simple and elegant best practice.

**Comment by elrido** [comment] 2018-05-27 14:07
I am talking of these industry standards that use full message IDs:
- XML:TM and Tmx and TermBase eXchange (TBX) ISO 30042:2008
- XLIFF (XML Localization Interchange File Format) OASIS
- Qt linguist

I think the pros and cons are more or less there. I still see only cons for doing this. Not to speak of the huge amount of work this would cause to change this all across the project.

I'm sorry, but I will now close this and rather spend my time working on getting this 1.2 release eventually out of the door. I would kindly ask you to also focus more on getting actual issues resolved.

We disagree, Ok, but this is not the end of the world and we still have already 12 translations with the current translation logic (not counting the English default, so 13 languages total). :tada:

**Closed by elrido** 2018-05-27 14:07 UTC

**Comment by micschk** [comment] 2018-06-06 11:33
(I understand there's more pressing issues currently which would be a reason to postpone this issue to some later date.) The issues I ran into while trying to contribute a Dutch translation were all caused by using full strings as keys. This has resulted in me spending way more time than necessary on a trivial task, and not being eager to maintain the translation. Time I could instead have spent on a different issue/code contribution.

That's why I've tried to suggest some improvements, I think some strong arguments for doing translations slightly different have been pointed out. From where I'm standing I don't see any convincing argument for using full textstrings as keys besides 'thats just how we (and some others) have been doing it all along'.

Looking at #201 I also see some confusion which could be prevented if a different system would be used (eg changing translation *keys* to use ellipsis or update the PHP version translation *key* to 5.4...)

My suggestion would be to have a translation function like: 
```translate('PHP_VERSION_WARNING', '%s requires php %s or above to work. Sorry.');```
So there's a default English version provided eg in case the current translation doesn't yet include a specific new string. No keys will have to be updated or anything.
And then a job/task/function/bash-oneliner or some mechanism which collects any calls to 'translate()' and displays them or adds them to the translation .yml file (at the bottom) if the keys are not yet included.

<img width="659" alt="screen shot 2018-06-06 at 12 51 13" src="https://user-images.githubusercontent.com/1005986/41034886-49dd7e80-698b-11e8-8257-a25e6ba886a5.png">
<img width="662" alt="screen shot 2018-06-06 at 12 51 45" src="https://user-images.githubusercontent.com/1005986/41034900-55c16dc4-698b-11e8-8e41-313f32c4fc2e.png">
<img width="673" alt="screen shot 2018-06-06 at 12 52 08" src="https://user-images.githubusercontent.com/1005986/41034905-594d67a4-698b-11e8-8b58-e6ff7c6902d7.png">
