### ISSUE TITLE
More info for opengraph

### ISSUE THREAD

**Issue by ZerooCool** [PrivateBin/PrivateBin#677] opened 2020-08-11 13:34 UTC
#651 

1-
Need add this, in !
`<html>`
by
`<html prefix="og: https://ogp.me/ns#" >`

2-
O.o !
**I see, if robots.txt deny all robots, then, the card validator from twitter can't work, then, Opengraph doesn't work !**
https://cards-dev.twitter.com/validator
**It's really a problem from Twitter !**

3-
It's better to use image 200 =< for facebook :
```
<meta property="og:image" content="REAL PATH FROM IMAGE" />
<meta property="og:image:type" content="image/png" />
<meta property="og:image:width" content="200" />
<meta property="og:image:height" content="200" />
```

**Comment by rugk** [comment] 2020-08-11 13:53
Yeah, no need to open yet another issue. Post that information in https://github.com/PrivateBin/PrivateBin/issues/651 or better, in https://github.com/PrivateBin/PrivateBin/pull/668, so it can be included in the PR.

Or, if you have adjusted all that in your local instance, you can always create a PR of course.

**Comment by rugk** [comment] 2020-08-11 13:53
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/651

**Closed by rugk** 2020-08-11 13:53 UTC
