### ISSUE TITLE
suggestion: direct link for raw text

### ISSUE THREAD

**Issue by meanssaddles** [PrivateBin/PrivateBin#984] opened 2022-09-29 08:31 UTC
currently raw text just show all text in an empty background and it need user interaction, which i cannot directed link to the raw text itself (it will link to the paste page) which is actually useless for my use case (i use them for custom rule for umatrix/ublock origin extension, which currently i use pastebin raw mode to link to the raw text of the paste)

it would be nice to have additional dedicated raw text directed link instead so the program can read them (probably need to be disabled on password protected paste)

here is example of pastebin raw text which i can't do with privatebin https://pastebin.com/raw/617gSfFN

**Comment by r4sas** [comment] 2022-09-29 15:35
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/234

**Closed by r4sas** 2022-09-29 15:35 UTC
