### ISSUE TITLE
How to enable copy/past password from the buffer when need to decrypt the paste? 

### ISSUE THREAD

**Issue by LizaChernysh** [PrivateBin/PrivateBin#565] opened 2020-01-15 19:02 UTC

**Comment by r4sas** [comment] 2020-01-15 19:20
Are you about password entering field in state when paste can't be decrypted?

**Comment by LizaChernysh** [comment] 2020-01-16 09:44
I'm about pass entering field when need to enter password to decrypt

**Comment by rugk** [comment] 2020-01-20 14:37
Could you please describe what you want to do in some simple steps, i.e. 1. -> 2. -> 3. etc.?

**Comment by LizaChernysh** [comment] 2020-01-20 15:10
1. I create a paste with a password and generate a link 
2. Open this link 
3. I see a form that requires enter the password to decrypt my message. But my pass is long and I would like to put it from a buffer(Ctrl+V). However, I couldn't. I can enter pass only manually. 
4. On https://privatebin.net/ I couldn't reproduce this problem. Maybe, some configuration on our side is blocking this functionality. But I couldn't understand what exactly.

**Comment by rugk** [comment] 2020-01-21 18:44
Indeed, there is no functionality that prevents you from pasting your password.

This has to be some problem on your/the instance you are using or a problem locally in your browser. (add-ons/extensions?)

So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.

**Closed by rugk** 2020-01-21 18:44 UTC
Labels: question

**Comment by rugk** [comment] 2021-04-10 14:34
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/595
