### ISSUE TITLE
private mode

### ISSUE THREAD

**Issue by MatthiasKammerlohr** [PrivateBin/PrivateBin#366] opened 2018-10-15 12:28 UTC
Hi, 

can I switch to a mode or something where only internal users can create new text?
Internal and external users have to read it.

Many thanks!

**Comment by rugk** [comment] 2018-10-15 16:54
I guess this was already asked/explained in https://github.com/PrivateBin/PrivateBin/issues/136, so closing as a dupe of https://github.com/PrivateBin/PrivateBin/issues/136.

Let me know if this is not what you wanted to do.

**Closed by rugk** 2018-10-15 16:54 UTC
