### ISSUE TITLE
Could not create paste: server error or not responding

### ISSUE THREAD

**Issue by tryingtosetup** [PrivateBin/PrivateBin#292] opened 2018-03-24 08:35 UTC
Having this error when trying to set up this project.

"Could not create paste: server error or not responding"

I have followed the installation guides down to the letter. Is there still and issue with running this on PHP 7.0? However I'm thinking the installation guide is pretty out of date as I have picked up on some issues.

"In the file cfg/conf.php you can configure PrivateBin. A cfg/conf.sample.php is provided containing all options and default values."

There isn't a cfg/conf.php in your files, you need to create one. When doing this the whole page goes blank, its only when cfg/conf.sample.php is located that I can actually see the template. So unsure what's going on there.

I ran the script for the permissions you wrote in the other thread of another user who is having the same problem, didn't seem to change anything.

Noticed that the password box doesn't come up when files are uploaded. (Sorted, noticed this was fixed when the script was ran)

Was using xampp to test it but no luck so switched to a ubuntu server still with no luck.

Error Log

PHP Fatal error:  Uncaught Exception: unable to create directory data in /var/www/html/lib/Persistence/AbstractPersistence.php:90\nStack trace:\n#0 /var/www/html/lib/Persistence/AbstractPersistence.php(73): PrivateBin\\Persistence\\AbstractPersistence::_initialize()\n#1 /var/www/html/lib/Persistence/TrafficLimiter.php(106): PrivateBin\\Persistence\\AbstractPersistence::_exists('traffic_limiter...')\n#2 /var/www/html/lib/PrivateBin.php(223): PrivateBin\\Persistence\\TrafficLimiter::canPass()\n#3 /var/www/html/lib/PrivateBin.php(135): PrivateBin\\PrivateBin->_create()\n#4 /var/www/html/index.php(18): PrivateBin\\PrivateBin->__construct()\n#5 {main}\n  thrown in /var/www/html/lib/Persistence/AbstractPersistence.php on line 90

By the looks of it, it has something to do with the Traffic limiter so maybe it's something to do with this
https://github.com/PrivateBin/PrivateBin/issues/42 but It's been tested with 5.6V PHP. I don't see how it can be a permission problem once I've change the permissions both manually and with the script provided.

Should the model be?

;[model]
;class = Database
;[model_options]
;dsn = "mysql:host=IPADDRESS;dbname=DATABASENAME;charset=UTF8"
;tbl = "pb_	; table prefix ***(pb_ or pb_paste?)
;usr = "USERNAME"
;pwd = "PASSWORD"
;opt[12] = true	  ; PDO::ATTR_PERSISTENT

Information changed for privacy.

Any ideas? Can provide server details so you can see first hand, as its just a tester.

**Comment by rugk** [comment] 2018-03-24 09:50
This is an exact duplicate of https://github.com/PrivateBin/PrivateBin/issues/291.

You have the same problem: PB cannot create the data dir.
So I've adjsuted [the script in the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#what-are-the-recommended-file-and-folder-permissions-for-privatebin) to alos create that dir and assign correct permissions. You still just have to edit the users, so they are correct.
Note that PrivateBin needs write access to the data dir.

BTW as far as what you've described the installation guide is correct:
> There isn't a cfg/conf.php in your files, you need to create one. 

Indeed, the guide states "You can copy it to `cfg/conf.php` and adapt it as needed.", this means the file is not there, it is just a template.

**Closed by rugk** 2018-03-24 09:50 UTC

**Comment by tryingtosetup** [comment] 2018-03-24 10:46
Couldn't see their error logs so wasn't sure if it was the same problem or not.

Solution didn't work but thanks anyway.

**Comment by rugk** [comment] 2018-03-26 12:27
So your issue is still the same. It's still the same issue with your server setup. PrivateBin cannot create the data dir.
Also running shell scripts blindly won't help. Better run command by command or so, or at least look at the script, understand it and check whether it works. You can also verify whether the dir is there or has been created.
So actually the script should create the dir, which PrivateBin still complains about. 

There is nothing at PrivateBin we can do about it. It's just a server/permission error. Please examine your setup and adjust it, or provide these/more information.
If you find an issue in the script, feel free to adjust it or suggest changes.
