### ISSUE TITLE
Adding a report mechanism

### ISSUE THREAD

**Issue by ImLunaHey** [PrivateBin/PrivateBin#1197] opened 2023-11-14 10:34 UTC
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Go to a page being used by crypto scammers
2. Look for report button

### What happens
There's no report button

### What should happen
There's a report button

## Additional information

People on twitter are using your site to host code used in crypto scams.
https://privatebin.net/?2f6c1102a6037614#ET7E2AiTwqPeZ2TRXo5dgrTagvVjYPoH1dcgifNsK7Vc

This is the scam they're pulling https://medium.com/coinmonks/mev-bot-scams-how-to-avoid-them-and-protect-your-funds-44088f80fb87

You can find your site listed in their description https://www.youtube.com/watch?v=ulORYmIhvfQ

## Basic information

**Server address**: N/A

**Server OS:** N/A

**Webserver:** N/A

**Browser:** N/A

**PrivateBin version:** N/A

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by elrido** [comment] 2023-11-14 18:48
privatebin.net is the demo instance for this open source software project. We do not intend to offer any web forms, but we do publish an abuse email address with our DNS whois entry for that domain or you can report abuse here in the issue tracker of the project, as you did.

The paste in question will expire within half a month (as of the time of this reply) and seems to contains source code which self-declares as being MIT licensed, so publishing it doesn't seem to put the project at legal risk.

As such, I do not see a reason to remove it, since as pure source code it is not directly executable. Someone wanting to participate in the scam would have to copy the code and compile, interpret or submit it to the environment they target. As long as we are not publishing proprietary source code that would open us up to legal trouble I do not see a reason to remove this content.

Should any of the other maintainers feel differently, please speak up here or contact me via email and we can take further action. I do not have any strong preferences either way, in this case.

**Comment by ImLunaHey** [comment] 2023-11-14 21:58
The code is run by victims and it then drains their wallets. Please remove the post.

**Comment by rugk** [comment] 2023-11-18 17:09
Anyway, please take and report such things to security [at] privatebin.org.

As for this issue itself, I agree a built-in option to report such content could be nice. It would also prevent people from sending us mails (via the above mail).

However, a server implementation would require a whole moderation backend, with approvals etc. The most simple option would be a report button that just opens a `mailto:` link, i.e. sends a mail to a pre-defined address (which the admin could set in a config).
In addition, IMHO, a simple web form could be done before where you can classify the report types (like what is the issue with radio buttons or so). This could then be included in the mail template automatically. The list for this should be defined in the backend in another flexible config, where you can add and remove entries.

**Comment by elrido** [comment] 2023-11-19 07:19
I really think this is out of scope for this project and we should focus our very thin resources on other areas, like upgrading bootstrap or getting rid of jquery.

**Comment by elrido** [comment] 2024-02-27 06:28
This seems to be a duplicate of #674 - closing this one to reduce the noise in the issue tracker.

**Closed by elrido** 2024-02-27 06:28 UTC
Labels: duplicate, enhancement, help wanted
