### ISSUE TITLE
Links in a new window

### ISSUE THREAD

**Issue by Warez2018** [PrivateBin/PrivateBin#360] opened 2018-09-06 17:44 UTC
Is it possible to have the option that the links open in another window? is not possible with a target blank or something similar? Please wait for your answer

**Comment by elrido** [comment] 2018-09-06 19:38
It is possible, yes, just as you describe, but it is [considered bad user interface design](https://css-tricks.com/use-target_blank/) and can even [be dangerous](https://mathiasbynens.github.io/rel-noopener/). Hence we did [implement the nofollow](https://github.com/PrivateBin/PrivateBin/blob/d66800b8ce53847fc3981502a0a7cddff1f41a2e/js/privatebin.js#L151), but not the target property in those links.

You can change that line in your instance if you prefer it that way. Remember to [regenerate the SRI hash](https://github.com/PrivateBin/PrivateBin/wiki/Development#subresource-integrity-for-javascript-resources) after you change the file. For the reasons given above I would advise against changing it in the main project. I would not mind a PR for a configurable option (i.e. by moving the HTML snippet of that line in to the [template area](https://github.com/PrivateBin/PrivateBin/blob/d66800b8ce53847fc3981502a0a7cddff1f41a2e/tpl/bootstrap.php#L525) in the template php files, so it can be configured server side), as long as it is not the default.

**Comment by rugk** [comment] 2018-09-06 21:02
Dupe of https://github.com/PrivateBin/PrivateBin/issues/61

**Closed by rugk** 2018-09-06 21:02 UTC
Labels: duplicate

**Comment by Warez2018** [comment] 2018-09-06 21:14
Thanks for your reply friends, but I did not understand what you wanted to say, I used rel = noopener and nooreferer and it has not worked to me, can you send me a capture of how the code would be? Sorry and thanks!!
