### ISSUE TITLE
Docker Conf.php doesn't get applied

### ISSUE THREAD

**Issue by SoulofSorrow** [PrivateBin/PrivateBin#826] opened 2021-08-12 14:34 UTC
Hello, I have the same problem my docker container does not load the config. Unfortunately I do not understand why. I have checked the mount path, the env variable and the config file. Do I have to pay attention to anything with docker?

**Comment by rugk** [comment] 2021-08-12 20:20
Wrong repository, but apparently you already found the correct one.

**Comment by rugk** [comment] 2021-08-12 20:20
Duplicate of https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/60

**Closed by rugk** 2021-08-12 20:20 UTC
