### ISSUE TITLE
Bootstrap 5 icons not displayed

### ISSUE THREAD

**Issue by janstieler** [PrivateBin/PrivateBin#1468] opened 2024-12-03 22:08 UTC
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

The SVG Sprites of Bootstrap 5 template will not be shown in Firefox 115.18.0esr (64-Bit)

## Steps to reproduce
Open privatebin in Firefox and the icons on the buttons are missing.

### What happens
The svg sprite links should shown the linked icons

### What should happen
The svg sprite links should shown the linked icons

## Additional information
![Screenshot 2024-12-03 at 22-55-18 PrivateBin](https://github.com/user-attachments/assets/39e9084f-ef85-414f-8599-1349a72de2fe)

## Basic information

**Server OS:** CentOS

**Webserver:** Apache

**Browser:** Firefox 115.18.0esr (64-Bit)

**PrivateBin version:** 1.7.5

I can reproduce this issue on <https://privatebin.net>: No (cant change the template)

**Comment by elrido** [comment] 2024-12-04 08:15
duplicate of #1347 & #1362 - as per comment there:

> That sounds like the CSP-related issue that we pointed out in the release notes and documented in the config file:
> 
> https://github.com/PrivateBin/PrivateBin/blob/0eae149474252d228af70b280fb1bd722e0fc499/cfg/conf.sample.php#L98-L99
> 
> Once we switch to bootstrap5 by default (hopefully by the end of this year or so), we can make this change the default for the CSP, but at the moment it would be an unnecessary relaxation for the bootstrap(3) and page ones.

You must already be using a conf.php to switch to that template, so you can just add/update the CSP rule in there to display the bootstrap5 images.

**Closed by elrido** 2024-12-04 08:15 UTC
Labels: duplicate, question/support
