### ISSUE TITLE
Suggestion: add ability to make site read-only.

### ISSUE THREAD

**Issue by alxpettit** [PrivateBin/PrivateBin#402] opened 2019-02-03 04:56 UTC
In a perfect world, I would like to make my site free for all to use who find it -- but I seem to be surprisingly good at making enemies. Thus, I can't allow everyone who can access to page to create pastes in my site.

This is a request to add a simple "log in to paste" feature -- without logging in, all read-only operations should be accessible, but no write operations. As a bonus, it could even support multiple accounts, so that I can let my friends use it, but not leave it as a free-for-all.

**Comment by rugk** [comment] 2019-02-03 10:19
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/384

**Closed by rugk** 2019-02-03 10:19 UTC
