### ISSUE TITLE
Page issue when deleting a post

### ISSUE THREAD

**Issue by bitog** [PrivateBin/PrivateBin#633] opened 2020-06-07 14:57 UTC
Hi there, 

When I delete a note I am getting the following screen:
_(simply the header and message box fully diapers)._

![img](https://i.imgur.com/KaptFN0.png)
 

**instead of:**
![img](https://i.imgur.com/h7ZM7QD.png)

Hope you have an idea what I can fix.

I use Cloudflare, not using any speed improvements (as mentioned in the FAQ)
and I didn't experienced this issue yesterday. It appeared after a domain swap. Did a fresh re-installation - didn't help either.

**Comment by rugk** [comment] 2020-06-08 08:56
Cannot reproduce on https://privatebin.net/

Also, please mind to use the bug issue template when reporting bugs.

I also hope you've read [our FAQ entry about Cloudflare](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-to-make-privatebin-work-when-using-cloudflare-for-ddos-protection).

**Comment by elrido** [comment] 2021-04-04 09:48
I think this question has been answered and I am closing the issue. Please feel free to reply if you have follow-up questions or create a separate issue for different topics.

**Closed by elrido** 2021-04-04 09:48 UTC
