### ISSUE TITLE
Links to other pastes don't work when clicked

### ISSUE THREAD

**Issue by Nothing4You** [PrivateBin/PrivateBin#969] opened 2022-08-22 10:18 UTC
## Steps to reproduce
1. Create paste
2. Copy URL of created paste
3. Insert URL of previously created paste into new paste
4. Click link in second paste

#### Firefox
<img width="511" alt="image" src="https://user-images.githubusercontent.com/3694534/185891952-029d0f12-28cc-4f83-b154-c4cdbcb1e5ae.png">

> Blocked Page
> 
> An error occurred during a connection to privatebin.net. 

#### Edge
<img width="294" alt="image" src="https://user-images.githubusercontent.com/3694534/185892062-28759cc3-9299-4844-8def-09874f8ad061.png">

> privatebin.net is blocked
> 
> privatebin.net refused to connect.
> 
> ERR_BLOCKED_BY_RESPONSE

#### Chrome
<img width="289" alt="image" src="https://user-images.githubusercontent.com/3694534/185892132-73e06131-4be0-4da9-af2f-df960a9cbde6.png">

> privatebin.net is blocked
>
> privatebin.net refused to connect.
>
> ERR_BLOCKED_BY_RESPONSE

#### Safari
Safari works just fine.

### What should happen

The first paste should load.

## Additional information

Example: https://privatebin.net/?235f120ad585593f#4akce4MxTPw3WD8YSwU7TWSxer9huGoGYcZnRRYhv9rg

See also https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/109 which for some reason got moved to the docker repo, but this issue affects the core PrivateBin application itself as well:

https://github.com/PrivateBin/PrivateBin/blob/628700afb14a908eb27bd9d5007869116db1f576/lib/Controller.php#L344

https://github.com/PrivateBin/docker-nginx-fpm-alpine/pull/108 removed the Cross-Origin-Opener-Policy header, but only in the container config.

## Basic information

**Server address**: https://privatebin.net/

**Server OS:** N/A

**Webserver:** N/A

**Browser:** Firefox 103.0.2, Edge 104.0.1293.63, Chrome 104.0.5112.101, Safari 15.6.1 (17613.3.9.1.16)

**PrivateBin version:** 1.4.0

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by rugk** [comment] 2022-08-22 11:21
Duplicate of https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/109

**Closed by rugk** 2022-08-22 11:21 UTC

**Comment by rugk** [comment] 2022-08-22 11:28
> Safari works just fine.

BTW that's omzteresting. Most propbably Safari [does not yet support the COOP header](https://webkit.org/blog/11648/new-webkit-features-in-safari-14-1/).
