### ISSUE TITLE
Direct raw mode access

### ISSUE THREAD

**Issue by seblu** [PrivateBin/PrivateBin#387] opened 2018-12-11 14:33 UTC
## Feature
Add an url endpoint (or argument) to share links with raw data rendering.

## Rationale
You may want to share an url with raw mode enabled to get the data without the privatebin interface. This is very useful to securely share documents like pdf or images which can be detected as they are by the browser and downloaded.

**Comment by rugk** [comment] 2018-12-11 15:22
Likely impossible security-wise as we cannot allow not sanitized HTML rendering or so and it would make phishing and other options possible.

What may rather be done is preventing access to creating new pastes for the user. Then this is a duplicate of https://github.com/PrivateBin/PrivateBin/issues/384. 
Also this may be a dupe of https://github.com/PrivateBin/PrivateBin/issues/386 or what else are you asking for here?

**Closed by rugk** 2018-12-11 15:22 UTC

**Comment by seblu** [comment] 2018-12-11 18:48
I understood that #384 is about restricted creation of paste to a subset of users. Where the topic here is to get a direct url to a raw content (or download link). So far, I don't think it's a duplicate.

I don't get what is unsecured with direct raw access (or download). Other paste service have such feature. Here is an example for a famous pastebin service: https://pastebin.com/raw/xqyD5G8x.

**Comment by rugk** [comment] 2018-12-11 19:13
Your Pastebin example serves **raw text**. Show me how they server a RAW HTML or image…

**Comment by rugk** [comment] 2018-12-11 19:15
Also again: What is your use case?

Note that it cannot be used with curl or so in our case. You would still need a browser and even if it's done I am not sure whether it would even be possible to trigger the browser's built-in PDF viewer or so…

But as this seems to be a dupe of https://github.com/PrivateBin/PrivateBin/issues/386, let's keep the discussion there.
