### ISSUE TITLE
Tor browser does not support Privatebin

### ISSUE THREAD

**Issue by mason1900** [PrivateBin/PrivateBin#537] opened 2019-10-27 05:13 UTC
## Steps to reproduce
Install and run a latest version or Tor browser. I am using `9.0 (based on Firefox 68.2.0esr)`.
Create a pad in a non-Tor browser. I use Firefox.
Copy the link to the Tor browser.

### What happens
It shows `error decompressing paste, due to missing WebAssembly support`.
The browser console shows `WebAssembly is not defined`.

### What should happen
It should work as normal.

## Basic information

**Server OS:** runnig the official docker image with version 1.3.1.

**Webserver:** nginx

**Browser:** Firefox and Tor browser

**PrivateBin version:** 1.3.1

I can reproduce this issue on <https://privatebin.net>: Yes 
Link: https://privatebin.net/?3948c4a075c3c5f6#Ec2jHgCKYPrqmRTVqPtj3GirwoDg4juTQDhi1dW5tCE2

**Comment by Haocen** [comment] 2019-10-27 05:35
You can disable zlib and compression in your server configuration.

**Comment by mason1900** [comment] 2019-10-27 05:39
Tor browser disabled wasm since 8.0:
https://trac.torproject.org/projects/tor/ticket/21549

**Comment by rugk** [comment] 2019-10-27 19:10
Duplicate of #454

**Closed by rugk** 2019-10-27 19:11 UTC

**Comment by umonaca** [comment] 2019-11-03 07:44
For anyone that wants to use Privatebin inside a Tor browser, here is the simple solution:

Go to `about:config`. Toogle `javascript.options.wasm` to `true` instead of the `false` by default. And that's it!
