### ISSUE TITLE
Exempt IPs from API rate-limit

### ISSUE THREAD

**Issue by rodehoed** [PrivateBin/PrivateBin#786] opened 2021-05-01 09:57 UTC
## Outline
We are using our PB in a semi-public way. Customers can make use of it and we also send pastes with it to our customers. To prevent possible abuse we have enabled the api ratelimit to 10. But our office should be exempted and should not be limited it by it.

## Steps to reproduce
1. Enable rate-limit
2. Send to many requests in a short time using the API
3. Error: Please wait 10 seconds between each post

## Proposed solution
The idea is we would like to add a feature so we can exempt IP addresses from hitting the rate-limit. This is something we can code ourselves and thus it's not the question you guys should add it. I just would like to have some feedback about before we add it; would the PR be accepted for example?

**Comment by rugk** [comment] 2021-05-01 22:11
This looks like a duplicate of https://github.com/PrivateBin/PrivateBin/issues/191.

However, first of all thanks for the incentive to create a PR. From my perspective, I’d have nothing against an extra setting for that, but let’s wait for @elrido’s opinion on that.

Also, let’s discuss it in the linked “original” issue.
In any case, I’ll close this as a dupe and thanks for your idea.

**Comment by rugk** [comment] 2021-05-01 22:11
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/191

**Closed by rugk** 2021-05-01 22:11 UTC

**Comment by elrido** [comment] 2021-05-02 05:04
PRs are certainly welcome. For a setting, it could be a simple, single IP match (for example, in the [setConfiguration()/getHash() functions](https://github.com/PrivateBin/PrivateBin/blob/2b8534d49e0a0b57511892e658dd75aa40e6a2e1/lib/Persistence/TrafficLimiter.php#L83): `self::setPermittedIp($conf->getKey('permitted', 'traffic')); / $_SERVER[self::$_ipKey] === self::$_ipPermitted;`) or a more complex one, allowing multiple IPs and subnets to be defined in an array - subnet to IP comparison requires different handling, depending on it being IPv4 or 6, check for [example how symfony does it](https://github.com/symfony/http-foundation/blob/5.x/IpUtils.php#L30-L152). Since that module is published on packagist, we could add it to our composer dependencies instead of rolling our own functions - it would raise the required PHP version to 7.2, though.
