### ISSUE TITLE
 Could not create paste: server error or not responding on Google Instance

### ISSUE THREAD

**Issue by keremcankabadayi** [PrivateBin/PrivateBin#631] opened 2020-05-30 11:37 UTC
## Steps to reproduce

1. I installed Privatebin with Docker on Google Cloud.
2. Trying to create new bin throwing me error.

### What happens
I'm getting ` Could not create paste: server error or not responding`

### What should happen
It should create new bin.

## Additional information

I'm creating container with 
`docker run --name privatebin -d --restart="always" -u 0 -p 8099:8080 -v /data/privatebin:/srv/data privatebin/nginx-fpm-alpine`

![image](https://user-images.githubusercontent.com/23381187/83327171-99eb3c00-a282-11ea-8edb-e2d6500c94f6.png)
Console:
```
error Internal Server Error privatebin.js:4422:25
    run https://privatebin4455.kabadayiapps.tools/js/privatebin.js?1.3.4:4422
    jQuery 4
```
Network:
![image](https://user-images.githubusercontent.com/23381187/83327183-b12a2980-a282-11ea-9f30-100a947379ea.png)

I'm using Nginx Proxy Manager with Let's Encrypt. It exposes `443` port but i'm not using it. I exposed `22, 80, 443, 8099` at my instance.

Here my container

![image](https://user-images.githubusercontent.com/23381187/83327243-0c5c1c00-a283-11ea-87ab-c80e7d9b0277.png)
 
## Basic information

**Server address**:
`privatebin4455.kabadayiapps.tools`

**Server OS:**
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Webserver:**

**Browser:**
Firefox 76.0.1 (32-bit)

**PrivateBin version:**
1.3.4
I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment] 2020-05-30 17:48
Could you please check what error occurs on the server side using:
```shell
docker logs privatebin
```
Usually there is a permission error displayed and you have to [adjust the permissions of the volume](https://github.com/PrivateBin/docker-nginx-fpm-alpine#running-the-image) (/data/privatebin on the docker host). If the server only receives an incomplete JSON (JSON related error message), your reverse proxy might mangle the POSTed message to the service.

**Comment by keremcankabadayi** [comment] 2020-05-30 18:57
Sorry my bad, I copied my container log but forgot to add.

```
2020/05/30 18:51:06 [error] 197#197: *108 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: unable to write to file /srv/data/.htaccess in /srv/lib/Persistence/AbstractPersistence.php:99,

**Comment by elrido** [comment] 2020-05-31 07:32
Ok, so it is a permission problem. The PHP process can't write to that folder. As per the containers README:

> Note that the volume mounted must be owned by UID 65534 / GID 82. If you run the container in a docker instance with "userns-remap" you need to add your subuid/subgid range to these numbers.

**Comment by rugk** [comment] 2020-05-31 13:39
Yet again another duplicate of https://github.com/PrivateBin/PrivateBin/issues/617 etc.

@elrido could we maybe investigate why we get so much of these bug reports for the same permission errors, maybe? Is it a problem in the docker container?

Closing as a dupe though…

**Closed by rugk** 2020-05-31 13:39 UTC

**Comment by elrido** [comment] 2020-05-31 13:50
It has to do with the webserver packages fixing those permissions for you upon installation. In the container we run without root permissions (so that we can support secure k8s / openshift environments) and that means the user has to fix those permissions in the volume attached for persistance themselves. This is documented and expected by experienced users, but maybe less by beginners.

I think we should expose that exception through the API so that it gets displayed in the web interface - this at least would make it clear that there is a permission issue and it avoids having to dig into the logs to figure that out.

**Comment by tarbib** [comment] 2023-08-11 16:19
Hello @elrido !
Stumbled on the same issue, thanks to ChatGPT output, I managed to run the container like this :
`docker run -d --restart="always" --read-only \
  -p 8080:8080 \
  -v privatebin-data:/srv/data \
  --user 65534:82 \
  privatebin/nginx-fpm-alpine:1.3.5
`

For absolute beginner like me this could be nice to have in your installation guide.

cheers!
