### ISSUE TITLE
Disabling the password feature breaks PrivateBin

### ISSUE THREAD

**Issue by 7adietri** [PrivateBin/PrivateBin#527] opened 2019-09-28 12:23 UTC
## Steps to reproduce

1. Install PrivateBin 1.3.1, configure `password = false`
2. Enter some text and hit "Send"

### What happens
PrivateBin shows an error message:
>  Could not create paste: server error or not responding

### What should happen
The paste should be created.

## Additional information

The browser console shows an error message:
> parsererror SyntaxError: "JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"
> privatebin.js:4053:25

## Basic information

**Server OS:** Ubuntu 18.04

**Webserver:** nginx, PHP 7.2

**Browser:** Firefox

**PrivateBin version:** 1.3.1

**Comment by elrido** [comment] 2019-09-28 15:08
Thanks for reporting. I could reproduce this. The JS logic seems to no longer recognize the disabled (=missing) password input field.

**Comment by abulgatz** [comment] 2019-10-13 16:52
Any time-frame on a fix?

**Comment by elrido** [comment] 2019-10-21 11:51
I don't think anyone started looking into it as there is no assignee. Presumably this regression snuck in during the big JS refactoring in 1.2 and so probably @rugk would know best how to solve this. If no-one has picked this up by the time of our next release, we should declare this feature to have been removed, get rid of the non-working config option and turn this into a request to re-add the feature.

**Comment by rugk** [comment] 2019-10-21 13:12
No, nothing to declare here. It's a bug and needs to be looked into, yes. I doubt it was removed in the JS refactoring, as I guess it would have been appeared before. Currently just have no time to look into this.

**Comment by Haocen** [comment] 2019-10-25 14:37
I cannot reproduce in 1.2.1, probably is introduced in recent release.

If you don't mind can you let me know your server address or paste your complete config here?

**Comment by Haocen** [comment] 2019-10-25 17:10
Fixed in https://github.com/PrivateBin/PrivateBin/pull/536

**Closed** 2019-10-26 04:05 UTC
