### ISSUE TITLE
psategin 1.3.2 long wait...

### ISSUE THREAD

**Issue by bgman111111** [PrivateBin/PrivateBin#583] opened 2020-02-04 20:47 UTC
I just update pastebin... and it comment loading... i follow manual change permissions on apache

#!/bin/sh
# directories of privatebin
pbpath='/var/www/pastebin'
pbdata='/var/www/pastebin/data'
# user, of PrivateBin and web server (may be the same, as explained above)
pbuser='www-data'
htgroup='www-data'
rootuser='www-data'

mkdir -p "$pbdata"

echo "chmod"
find "${pbpath}/" -type f -print0 | xargs -0 chmod 0640
find "${pbpath}/" -type d -print0 | xargs -0 chmod 0550
find "${pbdata}/" -type f -print0 | xargs -0 chmod 0640
find "${pbdata}/" -type d -print0 | xargs -0 chmod 0750

echo "chown"
chown -R ${rootuser}:${htgroup} "${pbpath}/"
chown -R ${pbuser}:${rootuser} "${pbdata}/"

is this correct.

**Comment by elrido** [comment] 2020-02-05 13:59
I can't answer that for sure, as I don't know what user and group your webserver and php process runs as. The use of www-data makes me guess that you might use Debian or one of it's derivatives? As long as the webserver userid can read the public directories and the php process manager (in case of apache and mod_php, that is also the webserver, but i.e. with php-fpm or fastcgi, that can be another userid entirely) has read access to cfg, i18n and lib and write access to the data, it should work.

If you do get an error, please check the php or webserver error logs, as they should contain the actual exception that gets thrown and indicate what file it has tried to access, but couldn't.

**Comment by bgman111111** [comment] 2020-02-06 00:28
Hey question. why you change what has worked. It is ubuntu server with php7.3-fpm

**Comment by elrido** [comment] 2020-02-06 21:10
What was changed? The last change that I remember we did that involved permissions was 1.1.1 in 2017...

Could you please provide the exact error message that your webserver or PHP fpm has logged? I'd like to help you, but you never explained what is failing and what errors you got. You are asking for file permissions, so which file was reported as not having sufficient permissions in the error?

**Comment by bgman111111** [comment] 2020-02-08 18:02
if i rember git cl9ne and it update 1.3.2 after that if comtinue l9ading... before 1.3.2 it was 1.3 andd it was workong... if i know what issue i will post apache2 dont comment erros. i had to revert version 1.2 for pastebin

**Comment by elrido** [comment] 2020-02-09 05:53
1.2 or 1.3?

**Comment by elrido** [comment] 2020-02-09 21:17
I'll close this for now as it doesn't nearly enough information to help figure out what the issue is. Please feel free to reopen this, once you got the error message from the webserver logs and if it doesn't clarify what file can't be opened or written into.

**Closed by elrido** 2020-02-09 21:17 UTC
Labels: question

**Comment by bgman111111** [comment] 2020-02-11 02:05
I solve it: When you make upgade be carefull not to change anything. As if i remember i had versoin 1.2 and after git update it change something in version 1.3.1 today i upgorade 1.3.2 and had to do something. If cases like this happend make recovery from old version. Your program is very good, but when make upgrade make it work from old version. If you make important changes, make step by step how it can be solved. There is users who like your program but are not developers. Maybe tomorrow monday you will say you stop project or you forget your github who will solve it. lINUX is shit becouse they make programs and dont know why they don't work. If you know linus tell him what i say. In ubuntu you can see that there is update of program but it will not work becouse it use old dependency... waiting how ? two years for a dependency to be update... when ubuntu had been updated... This happend in real life. there is other better privatebin... but your is much better. other is like pastebin... but i love your, include it can paste much code without bug... in other you paste the same code and it bug...  If you continue make this program good some days company like microsoft will come and buy it from you. In worse case will put you gun in head and you will give it to them free. This happend in 21 century... there is no law for richs... this is discrminations against all peoples. microsoft had buy github and much profiles has been deleted for they share TRUE mediatek source code. I accept it becouse, mediatek by law has to free they source code, include android has 2 years android upgrade. So mediatek 6735 has make ZERO official android upgrade. you buy smartphone 6735 becouse it cost 1xx euros and it come and stay on android 6... Do you know someone HOW much bugs has android 6... VERY... INCLUDE IT HAS WPA 2 bug that can infiltrate in WPA routers. YES and microsoft closed PEOPELS WHO TELL TRUE. who VIOLATE laws mediatek or peoples. For this who don't have brain mediatek VIOLATE SEVERALS LAWS. By law nobody is above law. femenism too is not above law.
