### ISSUE TITLE
Opening links in Edge prompts for password and invalidates link.

### ISSUE THREAD

**Issue by benkernan** [PrivateBin/PrivateBin#528] opened 2019-09-30 17:16 UTC
## Steps to reproduce

1. Create a privatebin link, ensure no password is set. 
2. Using Microsoft Edge browser, open a private bin link
3. If the link is not marked as "burn after reading", you can easily open the same link in Firefox / Chrome without a password prompt.

### What happens
User is prompted to enter a password to decrypt the link

### What should happen
The link is displayed, or a message is displayed telling the user to open the link in a different browser like Firefox. The link should stay valid, even if it's marked as "burn after reading".

## Basic information

**Server address**:

CentOS Linux release 7.7.1908 (Core)

httpd.x86_64                         2.4.6-90.el7.centos             @base                                                                                                                                                                   httpd-tools.x86_64                   2.4.6-90.el7.centos             @base  

Microsoft Edge 44.18362.1.0

1.3.1

I can reproduce this issue on <https://privatebin.net>: Yes / No
Yes

**Comment by elrido** [comment] 2019-09-30 18:14
This is a duplicate of #468 - as we discovered [over there](https://github.com/PrivateBin/PrivateBin/issues/468#issuecomment-520117147), Edge (non-Chromium) hasn't implemented SHA256 in Webcrypto, which makes it unable to de- or encrypt either the v1 or the v2 paste formats. You'll have to wait for MS to release the chromium based Edge and hope they don't restrict the webcrypto API in there.

**Comment by rugk** [comment] 2020-01-27 14:20
Reproduced this.
Okay so reopning this, because I do see the real issue here is not that Edge is not supported, but that our error handling is not smart enough to detect the case and show a proper error and instead misleads users with a password entry box. 🙄 

![grafik](https://user-images.githubusercontent.com/11966684/73182025-91d69080-4118-11ea-8f49-e8b7cab01b02.png)

**Comment by elrido** [comment] 2020-01-27 14:31
This issue will disappear with the chromium based edge. Since it is being released ATM, I don't think it is worth to invest time into this.

**Comment by rugk** [comment] 2020-01-27 14:55
### Likely problem

Legacy Edge implements some Web Crypto APIs, just [misses PBKDF2 support](https://github.com/PrivateBin/PrivateBin/issues/468#issuecomment-516299300).

## Technical solution

* detect whether we have PBKDF2 support?
* better: detect whether the browser supports all the algorithms of the Web Crypto API we need (i.e. more general)

## What should happen

The known ["browser unsupported"](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-it-show-me-the-error-privatebin-requires-a-modern-browser-to-work) error should be shown.

**Comment by rugk** [comment] 2020-01-27 14:55
we know Enterprises etc. I guess the legacy(tm) will stay there and somewhere someone will always use this old Edge.

Also if we can fix that properly, we of course fix it for all browsers, that maybe do not support all algos we use, but do support the Web Crypto API. 🤔

**Comment by elrido** [comment] 2020-01-27 15:01
Sure, add a feature detection for PBKDF2 around here-ish:
https://github.com/PrivateBin/PrivateBin/blob/3f8cf1792d573c8897b0baf84bf3472bb62633f7/js/legacy.js#L166-L177

**Comment by elrido** [comment] 2024-05-29 05:40
Do we still want to add this improved PBKDF2 detection, which would only cover legacy, non-chrome edge or can we close this as wont-fix?

**Closed** 2024-06-12 15:46 UTC
Labels: bug
