### ISSUE TITLE
Unable to open a pastebin due missing WebAssembly

### ISSUE THREAD

**Issue by mdziczkowski** [PrivateBin/PrivateBin#1104] opened 2023-06-23 16:13 UTC
I tryed to open a link to a private pastebin and while loading, I had recieved a following error message:

"Your browser doesn't support WebAssembly, used for zlib compression. You can create uncompressed documents, but can't read compressed ones."

## Environment

**Hardware**: Redmi 9A
**OS**: Android 12
**Browser**: TorBrowser (version i fo bellow)

102.2.1-Release (12.5) (Build #2015960777), 850f716365ea
AC: 102.0.14, e5b284fa02a1
GV: 102.12.0-20230707010101
AS: 93.1.0

===========
Before questioning: no, I cannot send the link to the pastebin... sorry

**Comment by elrido** [comment] 2023-06-24 05:25
Unfortunately, this problem is well understood: The Tor browser has webassembly disabled, for security reasons (it could be used to run an application in the browser that circumvents their proxy settings - leaking your real IP). You can therefore not decompress a compressed privatebin paste link in that browser, but you can create new pastes that wont be compressed, but still encrypted - as the message explains.

To read the message you got, you will have to either temporarily enable webassembly in the Tor browser (and disable it again after reading the message) or use a different browser and configure it to use Tor. You could also use one of the [third party clients](https://github.com/PrivateBin/PrivateBin/wiki/Third-party-clients) on the CLI to retrieve the message through Tor.

duplicate of #454

**Closed by elrido** 2023-06-24 05:25 UTC
Labels: duplicate
