### ISSUE TITLE
How does GET API work? I can't find GET api anywhere?

### ISSUE THREAD

**Issue by victoriaHan** [PrivateBin/PrivateBin#417] opened 2019-03-27 22:04 UTC
Hi,  I am trying to use API(https://github.com/PrivateBin/PrivateBin/wiki/API).
I found POST api (below)in privateBin.js to pass data to server. 

```
me.run = function()
        {
            $.ajax({
                type: 'POST',
                url: url,
                data: data,
                dataType: 'json',
                headers: ajaxHeaders,
                success: function(result) {
                    if (result.status === 0) {
                        success(0, result);
                    } else if (result.status === 1) {
                        fail(1, result);
                    } else {
                        fail(2, result);
                    }
                }
            })
            .fail(function(jqXHR, textStatus, errorThrown) {
                console.error(textStatus, errorThrown);
                fail(3, jqXHR);
            });
        }
```

and I can get the URL to use something like this 

> Your paste is http://127.0.0.1:8001/privatebin/single?234ad40b574278d2#fAe8t9cZ1gEBbRLRdk9rTU2FboImnY1V10oOcQ4bdNM= (Hit [Ctrl]+[c] to copy)

However, when I paste the url I got error in console like below. 

```
status changed:  Decrypting paste…
index.js:2177 parsererror SyntaxError: Unexpected end of JSON input
    at parse (<anonymous>)
    at Ut (jquery-3.3.1.js:formatted:3540)
    at k (jquery-3.3.1.js:formatted:3712)
    at XMLHttpRequest.<anonymous> (jquery-3.3.1.js:formatted:3839)
__stack_frame_overlay_proxy_console__ @ index.js:2177
(anonymous) @ privatebin_.js:3509
u @ jquery-3.3.1.js:formatted:1285
fireWith @ jquery-3.3.1.js:formatted:1338
k @ jquery-3.3.1.js:formatted:3722
(anonymous) @ jquery-3.3.1.js:formatted:3839
load (async)
send @ jquery-3.3.1.js:formatted:3847
ajax @ jquery-3.3.1.js:formatted:3695
window.jQuery.PrivateBin.me.run @ privatebin_.js:3491
window.jQuery.PrivateBin.me.getPasteData @ privatebin_.js:733
window.jQuery.PrivateBin.me.run @ privatebin_.js:4150
window.jQuery.PrivateBin.me.showPaste @ privatebin_.js:4297
window.jQuery.PrivateBin.me.init @ privatebin_.js:4464
(anonymous) @ VM11455 privatebin_.js:36
l @ jquery-3.3.1.js:formatted:1403
c @ jquery-3.3.1.js:formatted:1414
setTimeout (async)
(anonymous) @ jquery-3.3.1.js:formatted:1424
u @ jquery-3.3.1.js:formatted:1285
add @ jquery-3.3.1.js:formatted:1300
(anonymous) @ jquery-3.3.1.js:formatted:1429
Deferred @ jquery-3.3.1.js:formatted:1454
then @ jquery-3.3.1.js:formatted:1427
w.fn.ready @ jquery-3.3.1.js:formatted:1491
(anonymous) @ VM11455 privatebin_.js:33
index.js:2177 error message shown:  (2) ["Could not get paste data: %s", "server error or not responding"]
```

I can't find any 'GET' api 'Delete' API anywhere. How does it work when I paste the URL to see 'text' ?

**Comment by elrido** [comment] 2019-03-28 10:05
It is a regression in the current version of privatebin.js, that it is using a POST even to GET a paste. The server side API is flexible enough to do the right thing. This was addressed in the webcrypto branch and will no longer be the case in the next release.

Quick aside: We had to implement the API endpoint in the server rather flexible regarding the request type, since many webserver won't handle PUT or DELETE requests by default. Hence all requests also work as POST. What determines the request type really is the parameters that are sent. `data` implies a creation, `deletetoken` a deletion, etc.

The API endpoint (URL) is always the same. The only thing that changes is the request type and the parameters used. Note that in a GET request you encode the parameters as URL encoded URL parameters (?param1=value1&param2=value2 etc.) while in the POST you append the data in the body. jQuery will handle this for you, when choosing the correct type.

When you get a parser error, that would imply that the servers response got truncated. You should be able to check that in your browsers web developer tools in the "Network" tab by looking at the received response from the server for your API request.

I assume it is already understood, that the server will return base64 encoded, encrypted and compressed content and not plain text and that the privatebin.js will also handle the client side decoding, decryption and decompression of the message.

**Comment by victoriaHan** [comment] 2019-03-29 08:54
Thank you for the detail I understand.

**Comment by rugk** [comment] 2019-03-29 11:22
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.

**Closed by rugk** 2019-03-29 11:22 UTC
Labels: question
