### ISSUE TITLE
How to use the API with PHP properly?

### ISSUE THREAD

**Issue by flozzel** [PrivateBin/PrivateBin#526] opened 2019-09-24 09:02 UTC
I am trying to create a PrivateBin paste within a PHP-script. To achieve this, I want to send a request like the following:

      $url = 'my url to the PrivateBin installation';

      $data =
      [
        'v' => 2,
        'adata' =>
        [
          [
            'base64 encoded iv',
            'base64 encoded salt',
            100000,
            256,
            128,
            'aes',
            'gcm',
            'zlib'
          ],
        'plaintext',
        0,
        0
      ],
        'ct' => 'base64 of cipher text',
        'meta' => [ 'expire' => '5min' ]
      ];

      $options =
      [
        'http' =>
        [
          'method'  => 'POST',
          'content' => json_encode( $data ),
          'header'  => "Content-Type: application/json\r\n" .
                       "Accept: application/json\r\n"
        ]
      ];

      $context  = stream_context_create( $options );
      $result = file_get_contents( $url, false, $context );

      var_dump( $result );

Of course this is not working, because I need to specify the "base64 encoded iv", "base64 encoded salt" and "base64 of cipher text". But where do I get these from or do they have to be generated each time? I read the documentation/API but I can not figure out how to do this the proper way.

**Comment by rugk** [comment] 2019-09-24 09:46
I highly suggest you to read up a little on cryptography, i.e. what is an IV, a salt etc. These are AES things and always the same.

Also is this PHP?
If so, where exactly do you even encrypt things here?

**Comment by flozzel** [comment] 2019-09-24 10:41
Thank you for your fast answer.

Okay now I think it is a little clearer to me, so I can use any base64 encoded random string (everytime the same) for my salt and one (everytime a new) for the IV? And what is "base64 of cipher text" for?
Maybe you could show me an little example for the proper request data?

This code is part of a function for encrypting payment data at the end of a shop checkout. The usecase is a recurring bank transfer and the receiver should get an email with the link to the PrivateBin paste with the encrypted payment data so they can create the recurring bank transfer with it.

This unusual way of implementation is because of the European "General Data Protection Regulation", no bank data should been stored in a database. The receiver should view the PrivateBin paste with the bank data one time to create the recurring bank transfer and then the sensitive data is gone forever.

So in my example I will replace 'plaintext' with the user and payment data and from the request I want to get the link to the PrivateBin paste with the encrypted data. This link then gets send to the receiver in an email at the next step.

I hope it is now more understandable what I am up to.

**Comment by elrido** [comment] 2019-09-24 10:44
Be sure to generate salts and initialization vectors with a cryptographically safe random number generator - they have to be unique for every single generated paste. If using PHP 7 this can be done using [`random_bytes()`](https://www.php.net/manual/en/function.random-bytes.php).

It will probably help you to look at the example structure of a v2 paste that we use in our unit tests:
https://github.com/PrivateBin/PrivateBin/blob/d3153b5e38984a34346d037c8cd872c5e7defb00/tst/Bootstrap.php#L54-L76

Hope this helps.

**Comment by flozzel** [comment] 2019-09-24 13:06
Thank you, this is very helpfull. With this for example I am able to generate a paste and view it with:
https://myurl.com/?5b65a01b43987bc2#ME5JF/YBEijp2uYMzLZozbKtWc5wfy6R59NBb7SmRig=
But it asks me for a password to decrypt, with which parameter was is specified?

I am calling the PrivateBin paste with myurl + ? id parameter I got back from the request + # ct specified before doing the request.

And now of course I want to replace the salt etc. with my own. My idea was to do it like: base64_encode( random_bytes( 256 ) ); but this returns only an "Invalid data." I guess because the length is not correct. The length does match with the length given for kdf_keysize (256), cipher_tag_size (128). Has the string to be in the length random_bytes() or base64_encode() returns?

**Comment by elrido** [comment] 2019-09-24 14:17
The following explanation uses the terms defined in https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format - when you see a `term`, please check in that document what it is and what data it contains.

When you encrypt the contents of `paste_data_json`, which is itself a JSON encoded array (in PHP terms), to get the `cipher_text`, you need to provide the function ([`openssl-encrypt()`](https://www.php.net/manual/en/function.openssl-encrypt.php), for example) a key. But you don't pass it the raw key, but instead the `kdf_key` one generated by [using PBKDF2 key derivation](https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format#key-derivation-pbkdf2). This key is never sent to PrivateBin. Instead you take the raw random bytes that you feed into the key derivation, base64 encode them and append them to the URL after the hash ([see also](https://sebsauvage.net/wiki/doku.php?id=php:zerobin#how_does_it_work)).

The lengths required for all of these different randomly generated parts can also be found in the above linked document. In cryptographic functions sometimes bytes are used and sometimes bits, so I tried to always at comments (marked with `#`) to clarify which one it is.

A potential simplification to make your life easier: In the `paste_meta_json`, specify "none" as the compression type, then you don't have to deal with zlib compressing the `paste_data` into a `paste_data_blob`, before feeding it into your encryption function.

**Comment by r4sas** [comment] 2019-09-24 15:38
You must use passphrase (base64 of randomly generated bytes) after `#` in URL, which used for encrypting data.

**Comment by flozzel** [comment] 2019-09-26 10:22
Okay this really was not easy to figure out, but I am getting closer to it.
This is part of a bigger class, createPrivateBinPaste( $paymentProcess ) gets called first:


    private function createPrivateBinPaste( PaymentProcess $paymentProcess )
    {
     
      $url = 'https://myurltoprivatebin.com';

      $pasteData = '{ "paste": "text content of the paste" }';
      $password = '123456';

      $kdfSalt = openssl_random_pseudo_bytes( 8 );
      $iterations = 100000;
      $kdfKeyLength = 256;
      $kdfKey = openssl_pbkdf2( $password, $kdfSalt, $kdfKeyLength, $iterations, 'sha256' );
      $kdfKeyBase64 = base64_encode( $kdfKey );

      $keyLength = 128;
      $key = openssl_random_pseudo_bytes( $keyLength );
      $cipherData = $this->encryptData( $pasteData, $kdfKey );

      $cipherText = $cipherData[ 'cipherText' ];
      $cipherIV = $cipherData[ 'cipherIV' ];

      $data =
      [
        'adata' =>
        [
          [
            base64_encode( $cipherIV ),
            base64_encode( $kdfSalt ),
            100000,
            $kdfKeyLength,
            $keyLength,
            'aes',
            'gcm',
            'zlib',
          ],
          'plaintext',
          0,
          0,
        ],
        'meta' =>
        [
          'expire'  => '5min'
        ],
        'v'  => 2,
        'ct' => $cipherText,
      ];

      $options =
      [
        'http' =>
        [
          'method'  => 'POST',
          'content' => json_encode( $data ),
          'header'  => "Content-Type: application/json\r\n" .
                       "Accept: application/json\r\n"
        ]
      ];

      $context  = stream_context_create( $options );
      $result = file_get_contents( $url, false, $context );

      var_dump( $result );
    }

    private function encryptData( $data, $key )
    {
      $cipher = "aes-128-gcm";

      $ivlen = openssl_cipher_iv_length( $cipher );
      $iv = openssl_random_pseudo_bytes( $ivlen );
      $ciphertext = openssl_encrypt( $data, $cipher, $key, $options=0, $iv, $tag );

      return [ 'cipherText' => $ciphertext, 'cipherIV' => $iv ];
    }


This returns the following:

string(145) "{"status":0,"id":"543931dd65485902","url":"\/?543931dd65485902","deletetoken":"8d2e3e47e5a4039c92514a68610c0ce3c7aa2950628752618215a718d463a0d0"}"

Now what of this do I have to use for the key part (after the # ) to decrypt it and show the data?

**Comment by elrido** [comment] 2019-09-26 12:01
The URL of your paste would be:

```php
 $url . '/?543931dd65485902#' . base64_encode( $password );
```

Important: That `$password` MUST be a `openssl_random_pseudo_bytes( 32, true )` (it can be larger, but we recommend to use at least 32 bytes / 256 bit long keys, so the first block during AES GCM is encrypted with unique, random bits, even if key derivation would be discovered to have some flaw) and not a hardcoded string. It needs to be unique for every generated paste or otherwise anyone could reuse the password from one paste to decrypt any other paste.

Aside: If you can't use the more secure [`random_bytes()`](https://www.php.net/manual/en/function.random-bytes.php) of PHP >= 7, make sure that you request `crypto_strong` bytes from [`openssl_random_pseudo_bytes()`](https://www.php.net/manual/en/function.openssl-random-pseudo-bytes.php) by setting the second parameter to `true`. Otherwise you get non-cryptographically secure pseudo random numbers, which means your keys may be predictable or weaker.

**Comment by flozzel** [comment] 2019-09-26 13:34
Okay thank you for your further assistance.

I am running on PHP7 so I replaced my $password = '123456'; with $password = random_bytes( 32 ); and all other openssl_random_pseudo_bytes() also with the random_bytes() method.

Now with which passwort can I decrypt the message after opening the link (it asks me for a password even no one was specified) and how can I specify a password for decrypting the data after opening the link to view it?

**Comment by r4sas** [comment] 2019-09-26 14:33
> $url = 'https://myurltoprivatebin.com';

Better add trailing slash, because used POST.

> Now with which passwort can I decrypt the message after opening the link

Have you opened URL with `/?[id]#[base64_encode(password)]` part?
If you use correct link, but password is still required, that means that you have somwhere incorrect encryption code.

**Comment by flozzel** [comment] 2019-09-26 15:37
> Better add trailing slash, because used POST.

I dont add a trailing slash, because the $resultData[ 'url' ] already has a leading slash. 

> $kdfKeyBase64 = base64_encode( $kdfKey );

> Provided, but not used.

This is probably left over from my testing, or do I need the base64 encoded kdfKey somewhere?

> UPD: I think that here you must encode paste data, using adata with iv already filled inside

> $ciphertext = openssl_encrypt( $data, $cipher, $key, $options=0, $iv, NULL, $adata );

I will try this. The tag Parameter from openssl_encrypt has to be NULL? In the php documentation there is something about reference with GCM or CCM. In my adata, there is gcm specified. I do not know if this has anything to do with it. 

> Have you opened URL with /?[id]#[base64_encode(password)] part?

Yes I am generating the link like: 
echo $url . $resultData[ 'url' ] . '#' . base64_encode( $password );

I saw your updates and will try this first. Thank you :)

**Comment by r4sas** [comment] 2019-09-26 15:42
> The tag Parameter from openssl_encrypt has to be NULL?

Can it be that $tag will contain GCM tag at the end? Need to test what it will contain at the end, because in python realisation tag is returned by encryption function:
https://github.com/r4sas/PBinCLI/blob/682b47fbd3e24a8a53c3b484ba896a5dbc85cda2/pbincli/format.py#L262-L264

**Comment by r4sas** [comment] 2019-09-26 16:00
@flozzel at the end you need something like this:
```php
$CIPHER_ITERATION_COUNT = 100000;
$CIPHER_SALT_BYTES  = 8;
$CIPHER_BLOCK_BITS  = 256;
$CIPHER_BLOCK_BYTES = $CIPHER_BLOCK_BITS / 8;
$CIPHER_TAG_BITS    = $CIPHER_BLOCK_BITS / 2;
$CIPHER_TAG_BYTES   = $CIPHER_TAG_BITS / 8;

private function createPrivateBinPaste( PaymentProcess $paymentProcess )
{

  $url = 'https://myurltoprivatebin.com';

  $pasteData =
  [
    'paste' => 'text content of the paste'
  ];

  $password = openssl_random_pseudo_bytes( 32, true );

  $iv = openssl_random_pseudo_bytes( $CIPHER_TAG_BYTES )
  $salt = openssl_random_pseudo_bytes( $CIPHER_SALT_BYTES );

  $key = openssl_pbkdf2( $password, $salt, $CIPHER_BLOCK_BYTES, $CIPHER_ITERATION_COUNT, 'sha256' );

  $adata =
  [
    [
      base64_encode( $iv ),
      base64_encode( $salt ),
      $CIPHER_ITERATION_COUNT,
      $CIPHER_BLOCK_BITS,
      $CIPHER_TAG_BITS,
      'aes',
      'gcm',
      'none', // zlib or none
    ],
    'plaintext',
    0,
    0,
  ];

  // if you use zlib compression, you must add if here
  $paste = json_encode( $pasteData );

  $cipherText = openssl_encrypt( $paste, 'aes-128-gcm', $key, $options=0, $iv, $tag, $adata, $CIPHER_TAG_BYTES );

  $data =
  [
    'adata' => $adata,
    'ct' => base64_encode( $cipherText . $tag ),
    'meta' =>
    [
      'expire' => '5min'
    ],
    'v' => 2,
  ];

  $options =
  [
    'http' =>
    [
      'method'  => 'POST',
      'content' => json_encode( $data ),
      'header'  => "Content-Type: application/json\r\n" .
                   "Accept: application/json\r\n"
    ]
  ];

  $context  = stream_context_create( $options );
  $result = file_get_contents( $url, false, $context );

  var_dump( $result );
  echo 'Generated passhash is ' . base64_encode($password);
}
```

**Comment by flozzel** [comment] 2019-09-27 08:16
Hey @r4sas I tried your code (there is only a missing ; at 
`$iv = openssl_random_pseudo_bytes( $CIPHER_TAG_BYTES )`)
and the  `$cipherText = openssl_encrypt( $paste, 'aes-128-gcm', $key, $options=0, $iv, $tag, $adata, $CIPHER_TAG_BYTES );` excepts the $adata parameter to be a string, it is an array. 

Tried it as json_encoded or to omit the last two parameters so the code runs, but it keeps asking me for a password if I want to decrypt the paste. I do not really have an idea what is here expected for a the $adata param, the documentation says something about "Additional authentication data" for it.

**Comment by elrido** [comment] 2019-09-27 09:11
[Authenticated encryption](https://en.wikipedia.org/wiki/Authenticated_encryption) is a concept used in AES-GCM and other algorithms. Please read up on it's intent and it should became clear why and how we use it. In our case we want to only decrypt successfully, if the adata used to encrypt the paste and the one stored on the server are identical and unchanged - hence it has to be JSON encoded to the same format as is sent to / returned by the server in the encryption step.

**Comment by r4sas** [comment] 2019-09-27 10:57
Also base58 encoder needed for password instead base64...

**Comment by elrido** [comment] 2019-09-27 11:38
@r4sas Darn, you are correct. Forgot about that and I was the one implementing it. Sorry if that was the cause for those links not working. The JS implementation should try base64 if base58 fails, though, for v1 paste support.

**Comment by flozzel** [comment] 2019-09-30 08:42
> 
> 
> Also base58 encoder needed for password instead base64...
> 
> upd: Bit difficult understand what's wrong, seems like somewhere incorrect hashing or anything else?
> https://paste.i2pd.xyz/pbin-trunk/?c862b5e99707f2ed#GVKMHZVUWDCmZQBA66oCkFDkmifLo1mWyfuY5od7HTot (link for week)
> 
> upd2: reupload paste.

Tried it, is this working for you? It keeps asking me for a password.
I really do not have an idea how to get this running by my own.

**Comment by r4sas** [comment] 2019-09-30 10:32
> Tried it, is this working for you?

No. I don't understand why it is not working here. Maybe difference in encryption...

**Comment by elrido** [comment] 2019-09-30 18:39
Sorry you haven't achieved to implement this in PHP yet. Since this is cryptography you are dealing with binary data and debugging is non-trivial.

I assume you are already very close, but a detail is off. In such a case the message just fails to be decrypted, but its impossible for you to know if that is because an IV is off or the key is wrong or maybe the encoding is ascii instead where utf-8 is expected or the compression is the wrong type (hence the suggestion to first try it with compression "none" to eliminate this potential issue, as zlib compression comes in at least three different encapsulations and we use the raw one, not gzip or zlib).

What I can tell you from working on the python implementations of the format as well as when I reimplemented the v1 crypto in JS using the webcrypto API is that it helps when you create a test case with static, pre-generated data. You can capture a JSON payload that the JS frontend sends to the server as a POST request in your browsers development console and perform "divide et impera" on it:
- Using this JSON and the hash that was generated you have a valid message as a starting point and a sample to compare against.
- Then you can take it apart and see if you can generate the exact same JSON string from the individual variables.
- Then you go a step further and ensure you can generate the same base64 from the (static) numbers for IV, key, etc.
- Then you can check if you can recreate the ct using your crypto functions and the (static) IV, key, etc. <- this is likely the part that is most difficult to recreate.
- When all that works, you can replace the static bits with random_bytes() of the correct lengths and you should still get a valid payload.

**Comment by elrido** [comment] 2019-10-01 14:37
Is it any better if you use 'aes-**256**-gcm' instead?

**Comment by r4sas** [comment] 2019-10-01 14:42
No, base64 different, but size same.

**Comment by flozzel** [comment] 2019-10-21 15:39
Meanwhile I am using an own implementation for encryption because my project is terminated, but maybe someone can work out how to get this running for the other PHP-people out there.

But a last general question about encryption: Can I save the tag and iv together with the encrypted data in my database? If I have understood correctly, the tag and iv alone are not enough to decrypt the data? My encryption key is hardcoded in the methods for encryption and decryption.
It is explicitly desired to always use the same key here.

Thank you for your support so far.

**Comment by rugk** [comment] 2019-10-22 07:03
> Can I save the tag and iv together with the encrypted data in my database? If I have understood correctly, the tag and iv alone are not enough to decrypt the data?

Yes, and yes.

> My encryption key is hardcoded in the methods for encryption and decryption.

That may be the bigger problem… :thinking: 
Usually you should always generate a new key for each paste.

**Comment by elrido** [comment] 2019-10-22 10:57
I understand that for debugging purposes you want to have as many variables as possible be static (I suggested this myself, earlier in the thread).

In production you **never** want the key be static. Consider that with a static key anyone that gets any of these URLs can decrypt any past and future documents. Even if in your company these pastes are only ever consumed by one person, that role may change at some point in time. While you can then change the key to ensure no new pastes can be decrypted by the former holder of that role, they still retain access to all past documents. If there is a unique key for every paste, anyone that gets access to that link can only ever decrypt exactly one document and not any new ones or past ones.

**Comment by rugk** [comment] 2019-10-23 08:14
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.

**Closed by rugk** 2019-10-23 08:14 UTC
Labels: question

**Comment by dausruddin** [comment] 2019-10-29 13:04
So a completely working code is the one @r4sas posted?

**Comment by r4sas** [comment] 2019-10-29 15:47
> So a completely working code is the one @r4sas posted?

No. Somewhere crypto is incorrect.
