### ISSUE TITLE
Message not completely shown in raw text view

### ISSUE THREAD

**Issue by VonKavalier** [PrivateBin/PrivateBin#367] opened 2018-10-18 13:04 UTC
## Steps to reproduce

1. Create a new bin with `test<it disappears>butnothere`
2. Click on the shareable link
2. Click on the "Raw text" button

### What happens
Characters between `<` and `>` are not displayed in raw text.
Value displayed is : `testbutnothere`

### What should happen
We should see the entire text : `test<it disappears>butnothere`

## Additional information
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21989855/47156202-def96f00-d2e6-11e8-99f9-1e61add3e1c1.png">
<img width="557" alt="image" src="https://user-images.githubusercontent.com/21989855/47156221-e7ea4080-d2e6-11e8-8d53-e1e645c97f62.png">

## Basic information

https://copycat.drycat.fr

**Browser:** Firefox Dev Edition : 64.0b1

**PrivateBin version:** 1.2.1

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by elrido** [comment] 2018-10-21 06:32
This seems a duplicate of  #358 and should already be fixed in the master branch and will be published in version 1.3.

**Closed by elrido** 2018-10-21 06:32 UTC
Labels: bug, duplicate
