### ISSUE TITLE
'name' in conf.php is ignored

### ISSUE THREAD

**Issue by hasufell** [PrivateBin/PrivateBin#329] opened 2018-06-19 12:42 UTC
## Steps to reproduce

1. set `name` in conf.php

### What happens

The changed name does not show up.

### What should happen

The changed name should show up.

## Basic information

**Server OS:** Gentoo, but PrivateBin runs in docker

**Webserver:** [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) as front proxy with the docker container of PrivateBin

**Browser:** tried with firefox 60.0.2 and chrome 67.0.3396.87

**PrivateBin version:** `privatebin/nginx-fpm-alpine:latest`

**Comment by elrido** [comment] 2018-06-19 14:46
This is not yet a released feature of 1.1.1, but will be in release 1.2. For now you have to modify the template or give us a few more weeks to finally push out the release. ;-)

**Comment by elrido** [comment] 2018-06-19 14:48
duplicate of [#303](https://github.com/PrivateBin/PrivateBin/issues/303#issuecomment-381346790)

**Closed by elrido** 2018-06-19 14:48 UTC
Labels: duplicate
