### ISSUE TITLE
Asked for password for huge paste

### ISSUE THREAD

**Issue by jangrewe** [PrivateBin/PrivateBin#471] opened 2019-08-05 21:28 UTC
## Steps to reproduce

1. Create a new paste from a very long document (e.g. https://paste.ubuntu.com/p/s9HtXJp9HS/)
2. Open the link that is created

### What happens
I get asked for a password, even though i didn't set one for the paste

### What should happen
I should be able to see the paste

## Additional information
If i provide a password, it doesn't work either.
If i create a paste from a reasonably short / normal length document, it works fine.

## Basic information

https://paste.faked.org/

Debian stretch

nginx 1.12.1

Firefox 68.0.1

1.3 (c66bff9d1bdb16a7a76ff8b3aed0f9a9d24fa7e0)

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment] 2019-08-06 05:09
As that content works on the 1.3 test site but not on that one server, there is likely an issue with the setup. When I test the creation on the test site, the POST request in the browsers network tab of the developer console reports a size of 88 KB, but on your site it's only 543 bytes?!? AFAIK the browser displays only the lengths reported in the headers and not actually measures the content length.

Is there a 301 0r 302 redirect configured on the server side or a rewrite? Maybe the buffer used for that on the web server isn't large enough. On the server of the test site we do increase the `client_max_body_size`, among other things:
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/etc/nginx/nginx.conf#L70

**Comment by elrido** [comment] 2019-09-23 10:30
Closing as we couldn't reproduce it and haven't gotten more details. Feel free to reopen when more information is available.

**Closed by elrido** 2019-09-23 10:30 UTC
