### ISSUE TITLE
Decrypting paste fails: window.atob "The string to be decoded is not correctly encoded"

### ISSUE THREAD

**Issue by Lmmb74** [PrivateBin/PrivateBin#436] opened 2019-05-29 02:08 UTC
## Steps to reproduce

1. Create a password protected paste
2. Open the generated link and put the password

### What happens
The page hangs on Decrypting paste... with any browser (Or at least with Google Chrome, Mozilla Firefox and Microsoft Edge) and the actual paste is never displayed.

### What should happen
The page should load the paste.

## Basic information

**Server address: None**

**Server OS: Windows 10 x64**

**Webserver: Bitnami Wampstack 7.3.2**

**Browser:**

**PrivateBin version: https://github.com/PrivateBin/PrivateBin/commit/87c77195138ac7d377f4c1da96f5e3dd59d6ce66**

I can reproduce this issue on <https://privatebin.net>: No

**Comment by rugk** [comment] 2019-05-29 08:48
Is there any error shown? Also in the browser console (F12)?

> I can reproduce this issue on https://privatebin.net: No

Why so? So it only happens on your instance?

**Comment by elrido** [comment] 2019-05-29 11:54
As none of the main devs of this project have Windows it will be difficult for us to reproduce this. Could you maybe test this with a docker container instead, if we released one? Does it work with your browsers on Windows on the test server that I provided over in the merge request?

**Comment by Lmmb74** [comment] 2019-05-29 19:17
Just checked the test server, and it happens there too.

**Comment by rugk** [comment] 2019-05-29 19:42
Does it work without a password?

**Comment by Lmmb74** [comment] 2019-05-29 21:35
Yes. Haven't tested with a Linux client though, bug happens on Windows client at least.

**Comment by elrido** [comment] 2019-05-30 04:38
Well, then we need someone with Windows to debug it. Good thing it isn't yet a released version, yet. I suggest you use the 1.2.1 version in the mean time.

For our reference: Could you list the browsers and their version that you used on Windows?

**Comment by elrido** [comment] 2019-05-30 07:16
I asked a friend that has Windows 7 and Firefox 65. He claimed not to have had trouble displaying either of the example pastes. :-?

**Comment by r4sas** [comment] 2019-05-30 10:30
I have Win 8.1, with Firefox ESR 60, Chrome 68, Opera 60 and can test it.
@Lmmb74 if you can, provide link to your instance where you have problem.

**Comment by Lmmb74** [comment] 2019-05-30 11:36
I would like to, but I can't because I have to claim a public ip from my isp u.u
And I tested on Windows 10 using Chrome 74, Firefox and Edge (have to check the versions but not at home right now)

**Comment by rugk** [comment] 2019-05-30 15:13
Wait… did you not you say it works with privatebin.net, too?

So then just use it for testing. But I doubt OS/browser matters, if you really tried it with various browsers. 
So again some questions:
* Are you sure you did not get any error messages? Please also open the console log (press F12 on your keyboard) and check there. Possibly provide a screenshot.
* Can you create a paste and send us the link?

**Comment by Lmmb74** [comment] 2019-05-30 17:59
[My private wampstack](https://ibb.co/ynMPfrk)
[Test server](https://ibb.co/ZdZ14RZ)

**Comment by rugk** [comment] 2019-05-30 18:09
Thanks. Also note you can also upload screenshots to GitHub directly (just paste them).

**Comment by Lmmb74** [comment] 2019-05-30 19:11
https://zerobin-test.dssr.ch/?ad4f64880c16b238#6SB89LH84DxPvFj9iSYAJPdwibKHVTz37Ye2L65UJHKG

**Comment by rugk** [comment] 2019-05-30 19:36
Is there any password?

**Comment by Lmmb74** [comment] 2019-05-30 19:54
1234

**Comment by rugk** [comment] 2019-05-30 20:06
Okay, thanks. So decrypting indeed does not work, so this has to be an issue at the encryption stage.

![grafik](https://user-images.githubusercontent.com/11966684/58661038-1c1aea80-8327-11e9-9561-a2a00397b49d.png)

I get a different error though.

```
 DOMException: "String contains an invalid character" privatebin.js:4557:29
    run https://zerobin-test.dssr.ch/js/privatebin.js?1.2.1:4557
```

**Comment by elrido** [comment] 2019-05-31 04:50
Thank you all for investigating and collecting samples.

The error is caught in line 4557, but [thrown in line 1061](https://github.com/PrivateBin/PrivateBin/blob/c4b84b2b6bd8d0ff51b0c2189f6decb3a9598679/js/privatebin.js#L1061) (Chromium gives a longer stack trace in its console). This occurs when the base64 encoded IV and salt are being unpacked. The values in this example URL are:
- IV dNQ9WzIcuRCfMbxX14olCw==
- salt jAEdP\/HNxCI=

I can decode both of these in the firefox and chromium using atob as well as on the shell using the base64 binary. Maybe on the second decryption attempt (after asking for the password) the ciphermessage is passed in incomplete?

**Comment by elrido** [comment] 2019-05-31 05:09
Ok, so the second time around the two values already are decoded, because I forgot that [in JS assigning arrays to another variable passes the reference instead of a copy](https://www.samanthaming.com/tidbits/35-es6-way-to-clone-an-array).

On the test server I now have your paste decrypting properly, after the password is entered, in Chromium and Firefox. I would appreciate it if we could have some more testing of this before we close this ticket.

**Comment by r4sas** [comment] 2019-05-31 09:10
Tested on Chromium 67 under Win 8.1 - now works.

**Closed** 2019-05-31 12:21 UTC
Labels: bug
