### ISSUE TITLE
PDF's not displaying in Chrome or Chromium Edge

### ISSUE THREAD

**Issue by mbressman** [PrivateBin/PrivateBin#610] opened 2020-04-23 04:43 UTC
## Steps to reproduce
1. Attach a PDF to a paste
2. Load the paste URL into Chrome or Chromium Edge
3. See that there is a lot of empty space between the download attachment button and the paste text (if any) where presumably the PDF preview would go, but it's not showing up

### What happens
Something preventing PDF preview from showing up in Chrome and Chromium Edge - works OK in Firefox though

### What should happen
You should see the PDF preview in Chrome and Chromium Edge the same as you do in Firefox.

## Additional information
I think this is somewhat mentioned in https://github.com/PrivateBin/PrivateBin/pull/182 but I am not savvy enough to understand the full scope.

## Basic information

**Server address**: I don't want to enter the URL of my private server, but can provide via some secure messaging if necessary (where I have attachments enabled and this issue is occurring)

**Server OS:** CENTOS 7.7

**Webserver:** Apache 2.4.43

**Browser:** Numerous browser versions tested

**PrivateBin version:** 1.3.4

I can reproduce this issue on <https://privatebin.net>: No (since attachments aren't enabled)

**Comment by rugk** [comment] 2020-04-23 07:32
We should probably detect this and not preview it in Chrome/ium.

**Comment by elrido** [comment] 2021-04-04 10:25
So, I finally found out that this is due to us enabling the sandbox mode via our default CSP header and that Chrome in that mode disabling plugins, including it's built in PDF viewer. Unfortunately, it seems they consider this a "wont fix" issue: https://bugs.chromium.org/p/chromium/issues/detail?id=413851

One can work around it by changing the cspheader setting in the `conf.php` file. Remove the whole section in the line that starts with `sandbox` and add `frame-src blob:` instead. This let's Chrome display the PDF as intended.

Since this workaround weakens the security of the application and the Chrome team doesn't seem to consider this combination something they want to allow (PDFs being able to execute JS and inject HTML, so not considered to be safe to display in a sandbox), I'll close this issue as a "wont fix".

Please do report here, if Chrome does offer a new or different mechanism to preview PDFs in a sandboxed website that we can implement.

**Closed by elrido** 2021-04-04 10:25 UTC
Labels: bug
