### ISSUE TITLE
curl examples @ api

### ISSUE THREAD

**Issue by theonlydoo** [PrivateBin/PrivateBin#143] opened 2016-12-09 14:53 UTC
The [API documentation](https://github.com/PrivateBin/PrivateBin/wiki/API) doesn't provide any usage example with `curl` command or else.  It'd be pretty handy to provide some!

**Comment by rugk** [comment] 2016-12-09 20:24
Closing as a duplicate of https://github.com/PrivateBin/PrivateBin/issues/141.

**Closed by rugk** 2016-12-09 20:24 UTC
