### ISSUE TITLE
If you disable fileupload, uploading via the API still works but decryption fails

### ISSUE THREAD

**Issue by cryptomilk** [PrivateBin/PrivateBin#459] opened 2019-07-12 08:00 UTC
## Steps to reproduce
1. In the config file, set `file upload = false`
2. Upload an attachment using e.g. a command line client to upload paste with an attachment (which works)
3. Try to open the URL and it will fail because file uploading is disabled. It will decrypt it and then stop.

### What happens

It says `Decrypting paste` forever, however it successfully decrypted the paste and the attachment if you set a breakpoint in the js file.

### What should happen

If you upload an attachment via the API and `file upload = false`, the paste should be rejected with an appropriate error message.

**Comment by rugk** [comment] 2019-07-12 08:54
As the content is fully end-to-end encrypted, we cannot differenciate whether an upload has an attachment or just a big text part.

**Comment by cryptomilk** [comment] 2019-07-12 09:15
Add it to the metadata in v3?

**Comment by rugk** [comment] 2019-07-12 09:53
That would expose more information to the server than needed, whcih is something we should discuss. I.e. is the trade-off worth to expose more information? What do we gain?

Just to reject the paste?

If so, would not it be better to publicly expose to CLI clients whether the server has file uploads enabled, i.e. so the CLI client can directly reject it?

**Comment by cryptomilk** [comment] 2019-07-12 10:27
Yes, that also just came to my mind. We need an API to query server features!

**Comment by elrido** [comment] 2019-07-12 11:47
The problem isn't really the server capabilities, but the (web) client's capabilities. If the server lets you upload that paste with attachment, your client can still download and unpack it. But you have no guarantee that the web client or other third party clients support the same features. You could i.e. add additional fields into the `ct` and the web client will just ignore them and server won't even see them (we may use this, for example, if we implement the versioning, without breaking existing clients).

We do have some server feature detection already integrated in the current API, but the file upload capability of the web client is purely controlled by the template adding the file upload form field or not.

**Comment by elrido** [comment] 2020-01-05 16:14
I think this got addressed in a9bf667f8ecfc46116cccef836b8b35371dde378.

**Closed by elrido** 2020-01-05 16:14 UTC
Labels: bug
