### ISSUE TITLE
Do not burn after reading if the decryption key is wrong

### ISSUE THREAD

**Issue by jsarenik** [PrivateBin/PrivateBin#620] opened 2020-05-06 11:16 UTC
There are some similarities to https://github.com/PrivateBin/PrivateBin/issues/245
but this issue presents a much simpler approach and merely focuses on not deleting
the paste if it was not decrypted properly.

## Steps to reproduce

In order to delete a "Burn after reading" paste without knowing the key:

1. Go to any PrivateBin instance.
1. Create a new "Burn after reading" paste. Send.
1. Copy the resulting link to clipboard.
1. Open new tab. Paste the link, remove its last letter. This will render the key being wrong. Open. When it asks for password, just ignore it and close the tab.
1. Open another new tab. Paste the link, leave the correct key.

### What happens

`Could not get paste data.` - The paste is deleted just by trying to open it in step before the last one above, no matter if the password was right or not.

### What should happen

The paste should not be deleted if it is not decrypted properly.

## Additional information

One possible way to fix it is to add a new GET endpoint on the server-side that will be called by client-side `privatebin.js` when the paste is decrypted. If not correctly decrypted, the server will behave accordingly (by not deleting the paste):

1. User creates a "Burn after reading" paste.
1. A random token is generated.
  i. Hash of this random token is stored on server in a publicly non-accesible path.
  ii. The token itself is added into paste's JSON and encoded the same way as comments.
1. When another user opens the paste and uses a valid password the token mentioned above is read, decrypted and then a GET (containing either the hash or token itself) is sent to a particular endpoint which will make server delete the file. In case of normal (non-burn) paste, the endpoint can increment the number of successful reads of the paste.

Then another thing comes to my mind: There should be fake content and on clientside JS processing time connected with non-existing pastes. That would make it impossible to distinguish whether the paste exists or not.

## Basic information

**Server address**:
 * https://bin.snopyta.org (first in the public list - just for verification)
 * https://bin.bublina.eu.org (my server running [POSIX shell reimplementation of PrivateBin](https://github.com/jsarenik/bin.bublina.eu.org)
 * https://privatebin.net

**Server OS:**

```
# uname -srm
Linux 5.4.20-imx6 armv7l
```

**Webserver:**
Public-facing is Caddy2, but the main work is done by `busybox httpd`:

```
# /busybox/httpd --help 2>&1 | grep BusyBox
BusyBox v1.31.0 (2019-06-10 15:54:50 CEST) multi-call binary.
```
See https://github.com/jsarenik/bin.bublina.eu.org for more details. The served `privatebin.js` is the same as on normal PHP-run PrivateBin.

**Browser:**
Google Chrome Version 81.0.4044.129 (Official Build) (64-bit)

**PrivateBin version:**
1.3.4, also current master PrivateBin/PrivateBin@e59ef24

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by rugk** [comment] 2020-05-06 14:23
Thanks for the detailed report and ideas. Basically we already developed this idea in https://github.com/PrivateBin/PrivateBin/issues/245.

I'd rather solve that other issue that makes it much more useful in general.

Thus closing as a duplicate of https://github.com/PrivateBin/PrivateBin/issues/245.

**Closed by rugk** 2020-05-06 14:23 UTC

**Comment by jsarenik** [comment] 2020-05-10 12:09
OK. Have success with #245 then!
