### ISSUE TITLE
Attachment not downloading

### ISSUE THREAD

**Issue by jeremybreeschoten** [PrivateBin/PrivateBin#759] opened 2021-03-26 11:01 UTC
## Steps to reproduce

When i make a new secret link and attach a attachment it

### What happens
When i click on download Attachment nothing happens

### What should happen
DOwnload should start

## Additional information
When i right click on it and click on Save link as it works.

## Basic information

**PrivateBin version: 1.3.4**

I can reproduce this issue on <https://privatebin.net>: No

**Comment by rugk** [comment] 2021-03-26 12:08
If I need to guess this is the Chrome download issue with CSP headers, see https://github.com/PrivateBin/PrivateBin/issues/634#issuecomment-642149280. So ask your server admin to add the corresponding header.

Also please mind to fill out the issue template you choose, when you open an issue the next time. This makes it easier to troubleshoot issues or understand feature requests etc.

**Comment by rugk** [comment] 2021-03-26 12:09
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/634

**Closed by rugk** 2021-03-26 12:09 UTC
