### ISSUE TITLE
Prior page

### ISSUE THREAD

**Issue by m333w** [PrivateBin/PrivateBin#571] opened 2020-01-23 12:02 UTC
Hi all,

I upgraded my privatebin instance from 1.2.1 to 1.3.2 and I notice that now it is impossible with firefox or any other browser to go back. 

If you are on a site and you go to privatebin, it is then impossible to go back to the first visited site.  «Previous page»

On version 1.2.* I didn't have the problem, how can I solve it? 

Best regards

**Comment by rugk** [comment] 2020-01-23 17:08
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/503 ?

Please fill out the bug issue template to describe at what point you press back.

**Comment by m333w** [comment] 2020-01-23 17:22
Hi @rugk,
Thank's for your reply. I think is not exactly the same issue because in [#503](https://github.com/PrivateBin/PrivateBin/issues/503) the user have send something to privatebin. Here is not exactly the same, I am on domain.tld, if i go to privatebin.domain.tld i cant go back to domain.tld. 

But its seens the same effect of [#503](https://github.com/PrivateBin/PrivateBin/issues/503), i agree. 
So is not realy a issue, privatebin work like this now, if i undestand? 

Sorry for my bad english, i hope you can undestand me. 

Best regards.

**Comment by rugk** [comment] 2020-01-23 18:49
> I am on domain.tld, if i go to privatebin.domain.tld i cant go back to domain.tld.

That should work. Could you disclose the exact example?

Does it work if you again press "Back"?

Also again please note we have an issue template: https://github.com/PrivateBin/PrivateBin/blob/master/.github/ISSUE_TEMPLATE.md

**Closed** 2020-03-01 15:05 UTC
Labels: duplicate
