### ISSUE TITLE
links to other privatebin links on the same server generate an error instead of going to the page

### ISSUE THREAD

**Issue by manoflinux** [PrivateBin/PrivateBin#1016] opened 2022-11-08 02:31 UTC
## Steps to reproduce

1. create a paste with replies
2. create another paste 
3. create a reply on the paste with replies that has a link to the paste created in step 2.

### What happens
you will get this error "domainname.local is blocked domainname.local refused to connect.
ERR_BLOCKED_BY_RESPONSE"

### What should happen
you should be taken to the new paste in a new window instead of an error in a new window. 

## Additional information

But it does work if you right click and choose open in new tab. 

## Basic information

private .local domain

debian based 5.x kernel

**Webserver:** apache

**Browser:**
tried various, chrome, firefox, and others on linux and windows. 

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes 
privatebin.net is blockedprivatebin.net refused to connect.
ERR_BLOCKED_BY_RESPONSE

**Comment by manoflinux** [comment] 2022-11-08 02:38
example setup on public privatebin
https://privatebin.net/?194a01dbae5de8a8#5cHP4UvuZUwHMfDaL5prdGPATAVf29s6q5ajHgznWnm4

**Comment by manoflinux** [comment] 2022-11-08 02:40
![privatebin2](https://user-images.githubusercontent.com/6595620/200461906-e4bafc8e-24a5-4897-ae90-39df93f5a760.png)
![privatebin1](https://user-images.githubusercontent.com/6595620/200461908-bf926d91-5ba7-45fa-b19a-7e84ffe2d378.png)

**Comment by manoflinux** [comment] 2022-11-08 02:45
![privatebin1](https://user-images.githubusercontent.com/6595620/200462567-18ac534d-ee20-46f5-86e0-fed1efad250a.png)

**Comment by elrido** [comment] 2022-11-08 04:54
Duplicate of #970 - It's resolved but hasn't made it into a release. It requires a minimal change, if you want to resolve it on your instance:
https://github.com/PrivateBin/PrivateBin/blob/e740d0f761102209dc5bba92b5fe5f109bcd2c59/lib/Controller.php#L344-L347

**Closed by elrido** 2022-11-08 04:54 UTC
Labels: duplicate
