### ISSUE TITLE
Limit password protection attempts & make it configurable

### ISSUE THREAD

**Issue by thomasfrobieter** [PrivateBin/PrivateBin#509] opened 2019-08-29 16:39 UTC
I was wondering if you have endless tries to figure out the password?

Would be nice if where able to limit this by conf.php.

So.. something like: https://stackoverflow.com/questions/37120328/how-to-limit-the-number-of-login-attempts-in-a-login-script

**Comment by Haocen** [comment] 2019-08-30 05:15
Is this what you're looking for?
https://github.com/PrivateBin/PrivateBin/blob/master/lib/Persistence/TrafficLimiter.php

**Comment by elrido** [comment] 2019-08-30 08:40
The traffic limiter is a different feature that prevents more then one document/comment being created per IP per 10 seconds (default settings, can be adjusted or turned off) - this intends to prevent a single script kiddie to overflow your disk with pastes or to spam a discussion thread.

Reg. the OPs question: Since the server isn't involved at all in the decryption, **as soon as your client has downloaded a paste it has unlimited tries** and can brute force the password (I assume that such a client also has the key to the paste, as that is the second part needed to decrypt the paste).

We wanted to address this via a challenge token (see #245) that would be stored along side the paste on the server and only sending the client the paste if it can solve the challenge, proving it has both key and (optional) password. During the implementation of this idea in #447 we realized that this would leak too much information to the server and so didn't merge this implementation after all.

Remember that the primary goal of PB is to give the server hoster/operator plausible deniability of the contents of the pastes stored on their server. This is intended to serve as a legal mitigation in jurisdictions like France, where they would otherwise be forced to validate every single piece of uploaded material for copyright infringing or illegal content and otherwise take responsibility for what their users uploaded to their servers.

We felt that while the creator of a paste may prefer his (encrypted) paste not to fall into the hands of an adversary that can brute force the password (the key is a weak protection, as such an adversary very likely got the key already via the shared link), the risk for the server operators to be held responsible for the content because they could derive the key from the challenge outweighs this. Also, an adversary that has the computational means to crack your password offline very likely can get access to the server via legal or other means and get the paste that way if they want to get it. So this extra protection wouldn't really protect you in that case.

If anyone has an implementable solution for the above issues that were discussed in length in #245 and #447, please share these ideas in there and I am happy to take another crack at it, if it seams feasible to me.

**Comment by elrido** [comment] 2019-08-30 08:42
closing as a duplicate of #245 - feel free to pick up the discussion over there, after reviewing the above introduction to the issues we encountered during this.

**Closed by elrido** 2019-08-30 08:42 UTC
Labels: duplicate
