### ISSUE TITLE
Dark theme has bad visualization for json content

### ISSUE THREAD

**Issue by HLeithner** [PrivateBin/PrivateBin#254] opened 2017-10-23 14:17 UTC
## Steps to reproduce

1. Use the dark template
2. Make a new entry with json data
3. Use the source code highlighter

### What happens
First line is grey, Second is white. its hard to read

### What should happen
The white line should also be dark

## Additional information
https://privatebin.at/?43e3f4e10d85e6d6#FAvDEjk3Dv1Vy+LYKyEgnL4x6cEbAwNQbp7bWFxYsHI=
![image](https://user-images.githubusercontent.com/1497730/31891335-601c7f34-b806-11e7-9ee1-4d3bbe6fb56a.png)

## Basic information

**Server address**: https://privatebin.at

**Server OS:** Linux Debian 8.9

**Webserver:** Apache

**Browser:** Any

**PrivateBin version:** 1.1.1

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment] 2017-10-23 16:30
Are you using the [syntaxhighlightingtheme](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#syntaxhighlightingtheme) "sons-of-obsidian"?

**Comment by HLeithner** [comment] 2017-10-23 16:32
No, now its much better, thx ;-)

**Comment by rugk** [comment] 2017-10-25 19:00
Okay, so closing as a duplicate of https://github.com/PrivateBin/PrivateBin/issues/107.

**Closed by rugk** 2017-10-25 19:00 UTC
Labels: bug, UI/UX
