### ISSUE TITLE
private bin URL equal to sign issue

### ISSUE THREAD

**Issue by RockyBalboa333** [PrivateBin/PrivateBin#1038] opened 2022-12-28 10:31 UTC
## Steps to reproduce

1.
2.

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes / No

**Comment by elrido** [comment] 2022-12-28 16:58
@RockyBalboa333, could you please provide more information on what the issue is that you encounter? Based on the title alone one can only guess if this is a bug, a setup issue or a question that you have...

**Comment by rugk** [comment] 2022-12-30 17:44
Closing due to missing response.

**Closed by rugk** 2022-12-30 17:44 UTC
