### ISSUE TITLE
Support custom configuration path.

### ISSUE THREAD

**Issue by voronind-com** [PrivateBin/PrivateBin#1471] opened 2024-12-19 06:02 UTC
Issue: Currently you can only configure the app via php file inside the source files.

Desired: Allow to change the yaml configuration path i.e. with environment variable like `PRIVATEBIN_CONFIG=/path/to/config.php`.

Context: I'd like to package this repo for the Nixpkgs repository, but it won't get accepted unless the app allows separation of sources and configuration.

**Comment by elrido** [comment] 2024-12-19 07:26
This is possible via the [environment variable `CONFIG_PATH`](https://github.com/PrivateBin/PrivateBin/blob/master/doc/Installation.md#changing-the-config-path-only).

If you do manage to package it for Nix, please add a section into our [wiki referring to the package name and Distro](https://github.com/PrivateBin/PrivateBin/wiki/Other-installation-methods), so other users can find it.

closing as duplicate of #552

**Closed by elrido** 2024-12-19 07:26 UTC
Labels: duplicate

**Comment by voronind-com** [comment] 2024-12-20 04:27
> This is possible via the [environment variable `CONFIG_PATH`](https://github.com/PrivateBin/PrivateBin/blob/master/doc/Installation.md#changing-the-config-path-only).
> 
> If you do manage to package it for Nix, please add a section into our [wiki referring to the package name and Distro](https://github.com/PrivateBin/PrivateBin/wiki/Other-installation-methods), so other users can find it.
> 
> closing as duplicate of #552

Whoops, once I started, turned out it was already packaged before me just a few weeks ago. After all this time! Bummer.

**Comment by rugk** [comment] 2025-02-28 21:50
The entry on https://github.com/PrivateBin/PrivateBin/wiki/Other-installation-methods seems to be missing though, so if you have the details it would be great if you could add it there.

**Comment by voronind-com** [comment] 2025-03-01 06:32
> The entry on https://github.com/PrivateBin/PrivateBin/wiki/Other-installation-methods seems to be missing though, so if you have the details it would be great if you could add it there.

Will do

**Comment by voronind-com** [comment] 2025-03-01 06:44
@rugk Added a simple guide. Please tell me if I missed something. Thanks!
