### ISSUE TITLE
Any public API to use "bin"?

### ISSUE THREAD

**Issue by XinyueZ** [PrivateBin/PrivateBin#261] opened 2017-12-11 09:43 UTC

**Comment by rugk** [comment] 2017-12-11 10:05
Indeed, there is. [Have a look at the wiki](https://github.com/PrivateBin/PrivateBin/wiki/API).

Also there are multiple other open issues for that topic already, so closing this as a duplicate of https://github.com/PrivateBin/PrivateBin/issues/188.

**Closed by rugk** 2017-12-11 10:05 UTC
Labels: question

**Comment by XinyueZ** [comment] 2017-12-11 10:23
awsome
