### ISSUE TITLE
Cannot Download Files

### ISSUE THREAD

**Issue by tristanbolton** [PrivateBin/PrivateBin#702] opened 2020-10-07 15:59 UTC
## Steps to reproduce
1. Upload file (with or without password) - Feel free to use this one for testing https://email.bsiapp.ca/
2. Load the generated link in Chrome
3. Attempt to download the file, it will not work

### What happens
- File does not download
- Chrome console shows this error:

<img width="416" alt="Screenshot 2020-10-07 113437" src="https://user-images.githubusercontent.com/8730018/95353288-1923f880-0891-11eb-9930-3cc869c893df.png">
`Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details.`

## Basic information

**Server address**: https://email.bsiapp.ca/

**Server OS:** ubuntu-bionic-18.04-amd64-server

**Webserver:** Server version: Apache/2.4.29 (Ubuntu)

**Browser**: Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**PrivateBin version:** 1.3.4

I can reproduce this issue on <https://privatebin.net>: No - File Attachments is not enabled

**Comment by rugk** [comment] 2020-10-07 17:54
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/634

**Comment by rugk** [comment] 2020-10-07 17:54
Please follow the steps in the original issue, i.e. you/the server admins need(s) to adjust the csp setting.

**Closed by rugk** 2020-10-07 17:54 UTC

**Comment by tristanbolton** [comment] 2020-10-07 20:55
Thank you @rugk!
